// src/lib/storeProducts.ts

export interface StoreProduct {
  name: string;
  category: string;
  price?: number;
  unit?: string;
}

export interface Store {
  id: string;
  name: string;
  logo: string;
  color: string;
  products: StoreProduct[];
}

export const STORES: Store[] = [
  {
    id: 'colruyt',
    name: 'Colruyt',
    logo: '🔴',
    color: '#E31E24',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 1.09, unit: '1L' },
      { name: 'Boter', category: 'dairy', price: 2.49, unit: '250g' },
      { name: 'Eieren', category: 'dairy', price: 3.29, unit: '12 stuks' },
      { name: 'Griekse yoghurt', category: 'dairy', price: 1.79, unit: '500g' },
      { name: 'Geraspte kaas', category: 'dairy', price: 2.19, unit: '200g' },
      { name: 'Brood wit', category: 'bread', price: 1.89, unit: '800g' },
      { name: 'Brood volkoren', category: 'bread', price: 2.09, unit: '800g' },
      { name: 'Pistolets', category: 'bread', price: 1.49, unit: '6 stuks' },
      { name: 'Kipfilet', category: 'meat', price: 6.99, unit: '500g' },
      { name: 'Gehakt gemengd', category: 'meat', price: 4.49, unit: '500g' },
      { name: 'Hesp', category: 'meat', price: 2.99, unit: '200g' },
      { name: 'Zalm', category: 'fish', price: 5.99, unit: '200g' },
      { name: 'Tonijn blik', category: 'fish', price: 1.29, unit: '185g' },
      { name: 'Appelen', category: 'fruit', price: 2.49, unit: '1kg' },
      { name: 'Bananen', category: 'fruit', price: 1.69, unit: '1kg' },
      { name: 'Sinaasappels', category: 'fruit', price: 2.99, unit: '1kg' },
      { name: 'Tomaten', category: 'vegetables', price: 1.99, unit: '500g' },
      { name: 'Wortelen', category: 'vegetables', price: 1.29, unit: '1kg' },
      { name: 'Broccoli', category: 'vegetables', price: 1.49, unit: '1 stuk' },
      { name: 'Spinazie', category: 'vegetables', price: 1.99, unit: '400g' },
      { name: 'Paprika rood', category: 'vegetables', price: 0.99, unit: '1 stuk' },
      { name: 'Water plat', category: 'drinks', price: 0.49, unit: '1.5L' },
      { name: 'Fruitsap sinaasappel', category: 'drinks', price: 1.99, unit: '1L' },
      { name: 'Cola', category: 'drinks', price: 1.79, unit: '1.5L' },
      { name: 'Koffie gemalen', category: 'drinks', price: 3.99, unit: '250g' },
      { name: 'Chips naturel', category: 'snacks', price: 1.89, unit: '200g' },
      { name: 'Chocolade melk', category: 'snacks', price: 1.99, unit: '200g' },
      { name: 'Rijst', category: 'other', price: 1.99, unit: '1kg' },
      { name: 'Pasta spaghetti', category: 'other', price: 1.29, unit: '500g' },
      { name: 'Olijfolie', category: 'other', price: 4.99, unit: '750ml' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.49, unit: '1kg' },
      { name: 'Diepvries friet', category: 'frozen', price: 2.49, unit: '1kg' },
      { name: 'Wasmiddel', category: 'cleaning', price: 7.99, unit: '1.5L' },
      { name: 'Afwasmiddel', category: 'cleaning', price: 1.99, unit: '500ml' },
      { name: 'Shampoo', category: 'personal', price: 2.49, unit: '300ml' },
      { name: 'Tandpasta', category: 'personal', price: 1.99, unit: '75ml' },
    ],
  },
  {
    id: 'delhaize',
    name: 'Delhaize',
    logo: '🦁',
    color: '#E31837',
    products: [
      { name: 'Bio melk', category: 'dairy', price: 1.49, unit: '1L' },
      { name: 'Camembert', category: 'dairy', price: 2.99, unit: '250g' },
      { name: 'Verse room', category: 'dairy', price: 1.79, unit: '250ml' },
      { name: 'Griekse yoghurt', category: 'dairy', price: 1.99, unit: '500g' },
      { name: 'Brie', category: 'dairy', price: 3.49, unit: '200g' },
      { name: 'Mozzarella', category: 'dairy', price: 1.99, unit: '125g' },
      { name: 'Zuurdesembrood', category: 'bread', price: 3.49, unit: '400g' },
      { name: 'Croissants', category: 'bread', price: 2.99, unit: '4 stuks' },
      { name: 'Brood meergranen', category: 'bread', price: 2.49, unit: '800g' },
      { name: 'Kip biologisch', category: 'meat', price: 8.99, unit: '500g' },
      { name: 'Entrecote', category: 'meat', price: 12.99, unit: '300g' },
      { name: 'Salami', category: 'meat', price: 2.49, unit: '150g' },
      { name: 'Zalmfilet', category: 'fish', price: 7.99, unit: '200g' },
      { name: 'Garnalen', category: 'fish', price: 6.99, unit: '200g' },
      { name: 'Aardbeien', category: 'fruit', price: 3.49, unit: '500g' },
      { name: 'Mango', category: 'fruit', price: 1.99, unit: '1 stuk' },
      { name: 'Druiven', category: 'fruit', price: 3.99, unit: '500g' },
      { name: 'Avocado', category: 'vegetables', price: 1.49, unit: '1 stuk' },
      { name: 'Courgette', category: 'vegetables', price: 1.29, unit: '1 stuk' },
      { name: 'Sla gemengd', category: 'vegetables', price: 1.99, unit: '200g' },
      { name: 'Champignons', category: 'vegetables', price: 1.79, unit: '250g' },
      { name: 'Mineraalwater', category: 'drinks', price: 0.79, unit: '1.5L' },
      { name: 'Smoothie', category: 'drinks', price: 2.99, unit: '250ml' },
      { name: 'Thee assortiment', category: 'drinks', price: 3.49, unit: '25 zakjes' },
      { name: 'Prosecco', category: 'drinks', price: 7.99, unit: '750ml' },
      { name: 'Noten mix', category: 'snacks', price: 3.99, unit: '200g' },
      { name: 'Rijstwafels', category: 'snacks', price: 1.99, unit: '100g' },
      { name: 'Quinoa', category: 'other', price: 3.99, unit: '500g' },
      { name: 'Kokosolie', category: 'other', price: 5.99, unit: '500ml' },
      { name: 'Diepvries lasagne', category: 'frozen', price: 4.99, unit: '400g' },
      { name: 'Diepvries erwtjes', category: 'frozen', price: 1.99, unit: '1kg' },
      { name: 'Zeep vloeibaar', category: 'cleaning', price: 2.99, unit: '300ml' },
      { name: 'Wasverzachter', category: 'cleaning', price: 4.99, unit: '1L' },
      { name: 'Douchegel', category: 'personal', price: 2.99, unit: '250ml' },
      { name: 'Deodorant', category: 'personal', price: 3.49, unit: '150ml' },
    ],
  },
  {
    id: 'lidl',
    name: 'Lidl',
    logo: '🟡',
    color: '#0050AA',
    products: [
      { name: 'Melk vol', category: 'dairy', price: 0.89, unit: '1L' },
      { name: 'Boter goedkoop', category: 'dairy', price: 1.99, unit: '250g' },
      { name: 'Eieren', category: 'dairy', price: 2.49, unit: '10 stuks' },
      { name: 'Kwark', category: 'dairy', price: 0.99, unit: '500g' },
      { name: 'Snijkaas', category: 'dairy', price: 1.89, unit: '150g' },
      { name: 'Toastbrood', category: 'bread', price: 0.99, unit: '500g' },
      { name: 'Brood wit groot', category: 'bread', price: 1.29, unit: '1kg' },
      { name: 'Bagels', category: 'bread', price: 1.99, unit: '4 stuks' },
      { name: 'Kippenbouten', category: 'meat', price: 3.99, unit: '1kg' },
      { name: 'Worst', category: 'meat', price: 2.49, unit: '300g' },
      { name: 'Spek', category: 'meat', price: 1.99, unit: '150g' },
      { name: 'Vissticks', category: 'fish', price: 2.99, unit: '400g' },
      { name: 'Makreel blik', category: 'fish', price: 1.09, unit: '125g' },
      { name: 'Appelen zakje', category: 'fruit', price: 1.99, unit: '1.5kg' },
      { name: 'Bananen', category: 'fruit', price: 1.29, unit: '1kg' },
      { name: 'Aardappelen', category: 'vegetables', price: 1.99, unit: '2kg' },
      { name: 'Uien', category: 'vegetables', price: 0.99, unit: '1kg' },
      { name: 'Komkommer', category: 'vegetables', price: 0.79, unit: '1 stuk' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.49, unit: '1kg' },
      { name: 'Diepvries pizza', category: 'frozen', price: 2.99, unit: '400g' },
      { name: 'Diepvries friet', category: 'frozen', price: 1.99, unit: '1kg' },
      { name: 'Cola 6-pack', category: 'drinks', price: 3.49, unit: '6x330ml' },
      { name: 'Water 6-pack', category: 'drinks', price: 1.99, unit: '6x1.5L' },
      { name: 'Bier 6-pack', category: 'drinks', price: 4.99, unit: '6x33cl' },
      { name: 'Chips paprika', category: 'snacks', price: 1.49, unit: '200g' },
      { name: 'Koekjes', category: 'snacks', price: 0.99, unit: '200g' },
      { name: 'Pasta penne', category: 'other', price: 0.99, unit: '500g' },
      { name: 'Tomatensaus', category: 'other', price: 0.89, unit: '400g' },
      { name: 'Waspoeier', category: 'cleaning', price: 5.99, unit: '2kg' },
      { name: 'Toiletpapier', category: 'cleaning', price: 3.99, unit: '12 rollen' },
      { name: 'Scheerschuim', category: 'personal', price: 1.99, unit: '200ml' },
    ],
  },
  {
    id: 'aldi',
    name: 'Aldi',
    logo: '🔵',
    color: '#00539F',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 0.85, unit: '1L' },
      { name: 'Roomboter', category: 'dairy', price: 1.89, unit: '250g' },
      { name: 'Eieren', category: 'dairy', price: 2.29, unit: '10 stuks' },
      { name: 'Magere yoghurt', category: 'dairy', price: 0.79, unit: '500g' },
      { name: 'Gouda jong', category: 'dairy', price: 2.49, unit: '400g' },
      { name: 'Brood volkoren', category: 'bread', price: 1.19, unit: '800g' },
      { name: 'Croissants', category: 'bread', price: 1.99, unit: '6 stuks' },
      { name: 'Kip drumsticks', category: 'meat', price: 3.49, unit: '1kg' },
      { name: 'Rundergehakt', category: 'meat', price: 4.99, unit: '500g' },
      { name: 'Kippenfilet', category: 'meat', price: 5.99, unit: '500g' },
      { name: 'Bacon', category: 'meat', price: 2.29, unit: '150g' },
      { name: 'Zalm portie', category: 'fish', price: 4.99, unit: '200g' },
      { name: 'Tonijn blik', category: 'fish', price: 0.99, unit: '185g' },
      { name: 'Sinaasappels', category: 'fruit', price: 1.99, unit: '1kg' },
      { name: 'Appelen', category: 'fruit', price: 1.79, unit: '1kg' },
      { name: 'Tomaten', category: 'vegetables', price: 1.49, unit: '500g' },
      { name: 'Paprika mix', category: 'vegetables', price: 1.99, unit: '3 stuks' },
      { name: 'Prei', category: 'vegetables', price: 0.99, unit: '1 stuk' },
      { name: 'Diepvries spinazie', category: 'frozen', price: 1.29, unit: '450g' },
      { name: 'Diepvries friet', category: 'frozen', price: 1.99, unit: '1kg' },
      { name: 'Diepvries kip nuggets', category: 'frozen', price: 2.99, unit: '400g' },
      { name: 'Fruitsap', category: 'drinks', price: 1.49, unit: '1L' },
      { name: 'Koffie', category: 'drinks', price: 2.99, unit: '250g' },
      { name: 'Energy drink', category: 'drinks', price: 0.69, unit: '250ml' },
      { name: 'Chips', category: 'snacks', price: 1.29, unit: '200g' },
      { name: 'Chocolade', category: 'snacks', price: 0.99, unit: '100g' },
      { name: 'Rijst', category: 'other', price: 1.49, unit: '1kg' },
      { name: 'Bloem', category: 'other', price: 0.89, unit: '1kg' },
      { name: 'Suiker', category: 'other', price: 1.19, unit: '1kg' },
      { name: 'Afwasmiddel', category: 'cleaning', price: 1.49, unit: '500ml' },
      { name: 'Toiletpapier', category: 'cleaning', price: 2.99, unit: '8 rollen' },
    ],
  },
  {
    id: 'carrefour',
    name: 'Carrefour',
    logo: '🔷',
    color: '#004A97',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 1.05, unit: '1L' },
      { name: 'Boter gezouten', category: 'dairy', price: 2.29, unit: '250g' },
      { name: 'Eieren L', category: 'dairy', price: 3.49, unit: '12 stuks' },
      { name: 'Mascarpone', category: 'dairy', price: 2.49, unit: '250g' },
      { name: 'Emmentaler', category: 'dairy', price: 3.29, unit: '200g' },
      { name: 'Griekse yoghurt', category: 'dairy', price: 1.89, unit: '500g' },
      { name: 'Brood wit', category: 'bread', price: 1.79, unit: '800g' },
      { name: 'Baguette', category: 'bread', price: 0.99, unit: '1 stuk' },
      { name: 'Pistolets', category: 'bread', price: 1.59, unit: '6 stuks' },
      { name: 'Brood meergranen', category: 'bread', price: 2.29, unit: '800g' },
      { name: 'Kipfilet', category: 'meat', price: 7.49, unit: '500g' },
      { name: 'Gehakt rund', category: 'meat', price: 5.49, unit: '500g' },
      { name: 'Hesp gekookt', category: 'meat', price: 3.29, unit: '200g' },
      { name: 'Chorizo', category: 'meat', price: 2.99, unit: '150g' },
      { name: 'Zalmfilet', category: 'fish', price: 6.99, unit: '200g' },
      { name: 'Garnalen gepeld', category: 'fish', price: 5.99, unit: '150g' },
      { name: 'Kabeljauw', category: 'fish', price: 7.49, unit: '300g' },
      { name: 'Appelen', category: 'fruit', price: 2.29, unit: '1kg' },
      { name: 'Peren', category: 'fruit', price: 2.49, unit: '1kg' },
      { name: 'Aardbeien', category: 'fruit', price: 2.99, unit: '500g' },
      { name: 'Bananen', category: 'fruit', price: 1.59, unit: '1kg' },
      { name: 'Tomaten', category: 'vegetables', price: 1.89, unit: '500g' },
      { name: 'Sla', category: 'vegetables', price: 1.29, unit: '1 stuk' },
      { name: 'Wortelen', category: 'vegetables', price: 1.19, unit: '1kg' },
      { name: 'Broccoli', category: 'vegetables', price: 1.59, unit: '1 stuk' },
      { name: 'Courgette', category: 'vegetables', price: 1.19, unit: '1 stuk' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.69, unit: '1kg' },
      { name: 'Diepvries pizza', category: 'frozen', price: 3.49, unit: '400g' },
      { name: 'Diepvries vis', category: 'frozen', price: 4.99, unit: '400g' },
      { name: 'Cola', category: 'drinks', price: 1.89, unit: '1.5L' },
      { name: 'Mineraalwater', category: 'drinks', price: 0.59, unit: '1.5L' },
      { name: 'Fruitsap', category: 'drinks', price: 1.99, unit: '1L' },
      { name: 'Wijn rood', category: 'drinks', price: 5.99, unit: '750ml' },
      { name: 'Bier', category: 'drinks', price: 1.29, unit: '6x25cl' },
      { name: 'Chips', category: 'snacks', price: 1.79, unit: '200g' },
      { name: 'Chocolade puur', category: 'snacks', price: 1.49, unit: '100g' },
      { name: 'Noten', category: 'snacks', price: 2.99, unit: '200g' },
      { name: 'Pasta', category: 'other', price: 1.19, unit: '500g' },
      { name: 'Rijst', category: 'other', price: 1.89, unit: '1kg' },
      { name: 'Olijfolie', category: 'other', price: 4.49, unit: '750ml' },
      { name: 'Tomatenpuree', category: 'other', price: 0.99, unit: '200g' },
      { name: 'Wasmiddel vloeibaar', category: 'cleaning', price: 8.49, unit: '1.5L' },
      { name: 'Toiletpapier', category: 'cleaning', price: 4.49, unit: '12 rollen' },
      { name: 'Keukenrol', category: 'cleaning', price: 2.99, unit: '4 rollen' },
      { name: 'Shampoo', category: 'personal', price: 2.79, unit: '300ml' },
      { name: 'Douchegel', category: 'personal', price: 2.49, unit: '250ml' },
    ],
  },
  {
    id: 'spar',
    name: 'Spar',
    logo: '🌲',
    color: '#00843D',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 1.19, unit: '1L' },
      { name: 'Boter', category: 'dairy', price: 2.69, unit: '250g' },
      { name: 'Eieren', category: 'dairy', price: 3.49, unit: '10 stuks' },
      { name: 'Yoghurt natuur', category: 'dairy', price: 1.29, unit: '500g' },
      { name: 'Jonge kaas', category: 'dairy', price: 2.99, unit: '200g' },
      { name: 'Brood wit', category: 'bread', price: 2.09, unit: '800g' },
      { name: 'Brood volkoren', category: 'bread', price: 2.29, unit: '800g' },
      { name: 'Croissants', category: 'bread', price: 3.29, unit: '4 stuks' },
      { name: 'Kipfilet', category: 'meat', price: 7.99, unit: '500g' },
      { name: 'Gehakt', category: 'meat', price: 5.29, unit: '500g' },
      { name: 'Hesp', category: 'meat', price: 3.49, unit: '200g' },
      { name: 'Zalm', category: 'fish', price: 6.49, unit: '200g' },
      { name: 'Tonijn blik', category: 'fish', price: 1.49, unit: '185g' },
      { name: 'Appelen', category: 'fruit', price: 2.79, unit: '1kg' },
      { name: 'Bananen', category: 'fruit', price: 1.89, unit: '1kg' },
      { name: 'Sinaasappels', category: 'fruit', price: 3.19, unit: '1kg' },
      { name: 'Tomaten', category: 'vegetables', price: 2.19, unit: '500g' },
      { name: 'Komkommer', category: 'vegetables', price: 0.99, unit: '1 stuk' },
      { name: 'Paprika', category: 'vegetables', price: 1.19, unit: '1 stuk' },
      { name: 'Sla', category: 'vegetables', price: 1.49, unit: '1 stuk' },
      { name: 'Diepvries friet', category: 'frozen', price: 2.79, unit: '1kg' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.99, unit: '750g' },
      { name: 'Cola', category: 'drinks', price: 2.09, unit: '1.5L' },
      { name: 'Water', category: 'drinks', price: 0.89, unit: '1.5L' },
      { name: 'Bier', category: 'drinks', price: 5.49, unit: '6x33cl' },
      { name: 'Koffie', category: 'drinks', price: 4.49, unit: '250g' },
      { name: 'Chips', category: 'snacks', price: 2.09, unit: '200g' },
      { name: 'Chocolade', category: 'snacks', price: 1.79, unit: '100g' },
      { name: 'Pasta', category: 'other', price: 1.49, unit: '500g' },
      { name: 'Rijst', category: 'other', price: 2.19, unit: '1kg' },
      { name: 'Wasmiddel', category: 'cleaning', price: 8.99, unit: '1.5L' },
      { name: 'Afwasmiddel', category: 'cleaning', price: 2.29, unit: '500ml' },
      { name: 'Shampoo', category: 'personal', price: 3.29, unit: '300ml' },
    ],
  },
  {
    id: 'okay',
    name: 'OKay',
    logo: '🟠',
    color: '#F47920',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 0.99, unit: '1L' },
      { name: 'Boter', category: 'dairy', price: 2.19, unit: '250g' },
      { name: 'Eieren', category: 'dairy', price: 2.99, unit: '10 stuks' },
      { name: 'Yoghurt', category: 'dairy', price: 0.99, unit: '500g' },
      { name: 'Kaas blok', category: 'dairy', price: 2.79, unit: '300g' },
      { name: 'Brood wit', category: 'bread', price: 1.69, unit: '800g' },
      { name: 'Brood volkoren', category: 'bread', price: 1.89, unit: '800g' },
      { name: 'Pistolets', category: 'bread', price: 1.39, unit: '6 stuks' },
      { name: 'Kipfilet', category: 'meat', price: 6.49, unit: '500g' },
      { name: 'Gehakt gemengd', category: 'meat', price: 4.29, unit: '500g' },
      { name: 'Hesp', category: 'meat', price: 2.79, unit: '200g' },
      { name: 'Zalm', category: 'fish', price: 5.49, unit: '200g' },
      { name: 'Tonijn blik', category: 'fish', price: 1.19, unit: '185g' },
      { name: 'Appelen', category: 'fruit', price: 2.19, unit: '1kg' },
      { name: 'Bananen', category: 'fruit', price: 1.49, unit: '1kg' },
      { name: 'Tomaten', category: 'vegetables', price: 1.79, unit: '500g' },
      { name: 'Wortelen', category: 'vegetables', price: 1.09, unit: '1kg' },
      { name: 'Sla', category: 'vegetables', price: 1.19, unit: '1 stuk' },
      { name: 'Diepvries friet', category: 'frozen', price: 2.29, unit: '1kg' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.59, unit: '1kg' },
      { name: 'Cola', category: 'drinks', price: 1.69, unit: '1.5L' },
      { name: 'Water', category: 'drinks', price: 0.55, unit: '1.5L' },
      { name: 'Fruitsap', category: 'drinks', price: 1.79, unit: '1L' },
      { name: 'Koffie', category: 'drinks', price: 3.49, unit: '250g' },
      { name: 'Chips', category: 'snacks', price: 1.69, unit: '200g' },
      { name: 'Koekjes', category: 'snacks', price: 1.29, unit: '200g' },
      { name: 'Pasta', category: 'other', price: 1.09, unit: '500g' },
      { name: 'Rijst', category: 'other', price: 1.79, unit: '1kg' },
      { name: 'Olijfolie', category: 'other', price: 4.29, unit: '750ml' },
      { name: 'Wasmiddel', category: 'cleaning', price: 7.49, unit: '1.5L' },
      { name: 'Afwasmiddel', category: 'cleaning', price: 1.79, unit: '500ml' },
    ],
  },
  {
    id: 'albert-heijn',
    name: 'Albert Heijn',
    logo: '🌼',
    color: '#00A0E2',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 1.09, unit: '1L' },
      { name: 'Boter', category: 'dairy', price: 2.39, unit: '250g' },
      { name: 'Eieren', category: 'dairy', price: 3.19, unit: '12 stuks' },
      { name: 'Yoghurt', category: 'dairy', price: 1.49, unit: '500g' },
      { name: 'Gouda', category: 'dairy', price: 3.49, unit: '400g' },
      { name: 'Brood wit', category: 'bread', price: 1.99, unit: '800g' },
      { name: 'Brood volkoren', category: 'bread', price: 2.19, unit: '800g' },
      { name: 'Kipfilet', category: 'meat', price: 7.29, unit: '500g' },
      { name: 'Gehakt', category: 'meat', price: 4.99, unit: '500g' },
      { name: 'Hesp', category: 'meat', price: 3.19, unit: '200g' },
      { name: 'Zalm', category: 'fish', price: 6.79, unit: '200g' },
      { name: 'Garnalen', category: 'fish', price: 5.79, unit: '150g' },
      { name: 'Appelen', category: 'fruit', price: 2.39, unit: '1kg' },
      { name: 'Bananen', category: 'fruit', price: 1.59, unit: '1kg' },
      { name: 'Aardbeien', category: 'fruit', price: 3.29, unit: '500g' },
      { name: 'Tomaten', category: 'vegetables', price: 1.99, unit: '500g' },
      { name: 'Paprika', category: 'vegetables', price: 1.09, unit: '1 stuk' },
      { name: 'Broccoli', category: 'vegetables', price: 1.59, unit: '1 stuk' },
      { name: 'Avocado', category: 'vegetables', price: 1.39, unit: '1 stuk' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.79, unit: '1kg' },
      { name: 'Diepvries pizza', category: 'frozen', price: 3.99, unit: '400g' },
      { name: 'Cola', category: 'drinks', price: 1.99, unit: '1.5L' },
      { name: 'Water', category: 'drinks', price: 0.69, unit: '1.5L' },
      { name: 'Jus d\'orange', category: 'drinks', price: 2.29, unit: '1L' },
      { name: 'Koffie', category: 'drinks', price: 4.29, unit: '250g' },
      { name: 'Chips', category: 'snacks', price: 1.99, unit: '200g' },
      { name: 'Chocolade', category: 'snacks', price: 1.59, unit: '100g' },
      { name: 'Pasta', category: 'other', price: 1.29, unit: '500g' },
      { name: 'Rijst', category: 'other', price: 1.99, unit: '1kg' },
      { name: 'Wasmiddel', category: 'cleaning', price: 8.99, unit: '1.5L' },
      { name: 'Toiletpapier', category: 'cleaning', price: 4.99, unit: '12 rollen' },
      { name: 'Shampoo', category: 'personal', price: 3.49, unit: '300ml' },
    ],
  },
  {
    id: 'match',
    name: 'Match',
    logo: '🟥',
    color: '#C8102E',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 1.15, unit: '1L' },
      { name: 'Boter', category: 'dairy', price: 2.59, unit: '250g' },
      { name: 'Eieren', category: 'dairy', price: 3.39, unit: '12 stuks' },
      { name: 'Yoghurt', category: 'dairy', price: 1.39, unit: '500g' },
      { name: 'Kaas', category: 'dairy', price: 3.19, unit: '300g' },
      { name: 'Brood wit', category: 'bread', price: 1.99, unit: '800g' },
      { name: 'Baguette', category: 'bread', price: 1.09, unit: '1 stuk' },
      { name: 'Kipfilet', category: 'meat', price: 7.19, unit: '500g' },
      { name: 'Gehakt', category: 'meat', price: 4.99, unit: '500g' },
      { name: 'Hesp', category: 'meat', price: 3.09, unit: '200g' },
      { name: 'Zalm', category: 'fish', price: 6.29, unit: '200g' },
      { name: 'Tonijn', category: 'fish', price: 1.39, unit: '185g' },
      { name: 'Appelen', category: 'fruit', price: 2.39, unit: '1kg' },
      { name: 'Bananen', category: 'fruit', price: 1.69, unit: '1kg' },
      { name: 'Tomaten', category: 'vegetables', price: 1.89, unit: '500g' },
      { name: 'Sla', category: 'vegetables', price: 1.29, unit: '1 stuk' },
      { name: 'Wortelen', category: 'vegetables', price: 1.19, unit: '1kg' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.79, unit: '750g' },
      { name: 'Cola', category: 'drinks', price: 1.89, unit: '1.5L' },
      { name: 'Water', category: 'drinks', price: 0.69, unit: '1.5L' },
      { name: 'Wijn', category: 'drinks', price: 6.49, unit: '750ml' },
      { name: 'Chips', category: 'snacks', price: 1.89, unit: '200g' },
      { name: 'Chocolade', category: 'snacks', price: 1.49, unit: '100g' },
      { name: 'Pasta', category: 'other', price: 1.29, unit: '500g' },
      { name: 'Rijst', category: 'other', price: 1.99, unit: '1kg' },
      { name: 'Wasmiddel', category: 'cleaning', price: 8.49, unit: '1.5L' },
    ],
  },
  {
    id: 'intermarche',
    name: 'Intermarché',
    logo: '🔺',
    color: '#E2001A',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 1.05, unit: '1L' },
      { name: 'Boter', category: 'dairy', price: 2.39, unit: '250g' },
      { name: 'Eieren', category: 'dairy', price: 3.19, unit: '12 stuks' },
      { name: 'Yoghurt', category: 'dairy', price: 1.19, unit: '500g' },
      { name: 'Kaas', category: 'dairy', price: 2.99, unit: '300g' },
      { name: 'Brie', category: 'dairy', price: 3.29, unit: '200g' },
      { name: 'Brood wit', category: 'bread', price: 1.89, unit: '800g' },
      { name: 'Baguette', category: 'bread', price: 0.89, unit: '1 stuk' },
      { name: 'Kipfilet', category: 'meat', price: 6.99, unit: '500g' },
      { name: 'Gehakt', category: 'meat', price: 4.79, unit: '500g' },
      { name: 'Hesp', category: 'meat', price: 2.99, unit: '200g' },
      { name: 'Zalm', category: 'fish', price: 6.49, unit: '200g' },
      { name: 'Garnalen', category: 'fish', price: 5.49, unit: '150g' },
      { name: 'Appelen', category: 'fruit', price: 2.29, unit: '1kg' },
      { name: 'Bananen', category: 'fruit', price: 1.59, unit: '1kg' },
      { name: 'Tomaten', category: 'vegetables', price: 1.79, unit: '500g' },
      { name: 'Sla', category: 'vegetables', price: 1.19, unit: '1 stuk' },
      { name: 'Champignons', category: 'vegetables', price: 1.89, unit: '250g' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.69, unit: '1kg' },
      { name: 'Diepvries pizza', category: 'frozen', price: 3.29, unit: '400g' },
      { name: 'Cola', category: 'drinks', price: 1.79, unit: '1.5L' },
      { name: 'Water', category: 'drinks', price: 0.59, unit: '1.5L' },
      { name: 'Wijn rood', category: 'drinks', price: 5.49, unit: '750ml' },
      { name: 'Chips', category: 'snacks', price: 1.79, unit: '200g' },
      { name: 'Chocolade', category: 'snacks', price: 1.39, unit: '100g' },
      { name: 'Pasta', category: 'other', price: 1.19, unit: '500g' },
      { name: 'Rijst', category: 'other', price: 1.89, unit: '1kg' },
      { name: 'Olijfolie', category: 'other', price: 4.39, unit: '750ml' },
      { name: 'Wasmiddel', category: 'cleaning', price: 7.99, unit: '1.5L' },
      { name: 'Toiletpapier', category: 'cleaning', price: 3.99, unit: '12 rollen' },
    ],
  },
];