// src/lib/storeProducts.ts

export interface StoreProduct {
  name: string;
  category: string;
  price?: number;
  unit?: string;
  brand?: string;
}

export interface Store {
  id: string;
  name: string;
  logo: string;
  color: string;
  products: StoreProduct[];
}

export const STORES: Store[] = [
  {
    id: 'colruyt',
    name: 'Colruyt',
    logo: '🔴',
    color: '#E31E24',
    products: [
      // ZUIVEL - A-merken
      { name: 'Melk halfvol Campina', category: 'dairy', price: 1.15, unit: '1L', brand: 'Campina' },
      { name: 'Melk vol Campina', category: 'dairy', price: 1.19, unit: '1L', brand: 'Campina' },
      { name: 'Melk halfvol', category: 'dairy', price: 0.99, unit: '1L', brand: 'Boni' },
      { name: 'Melk mager', category: 'dairy', price: 0.95, unit: '1L', brand: 'Boni' },
      { name: 'Boter gezouten Président', category: 'dairy', price: 3.49, unit: '250g', brand: 'Président' },
      { name: 'Boter ongezouten Président', category: 'dairy', price: 3.49, unit: '250g', brand: 'Président' },
      { name: 'Boter', category: 'dairy', price: 2.29, unit: '250g', brand: 'Boni' },
      { name: 'Eieren L', category: 'dairy', price: 3.29, unit: '12 stuks', brand: 'Boni' },
      { name: 'Eieren M scharrelvlees', category: 'dairy', price: 3.99, unit: '12 stuks', brand: 'Boni' },
      { name: 'Eieren bio', category: 'dairy', price: 4.99, unit: '12 stuks', brand: 'Boni' },
      { name: 'Griekse yoghurt Fage', category: 'dairy', price: 2.49, unit: '500g', brand: 'Fage' },
      { name: 'Griekse yoghurt 0%', category: 'dairy', price: 1.79, unit: '500g', brand: 'Boni' },
      { name: 'Yoghurt natuur Danone', category: 'dairy', price: 1.99, unit: '500g', brand: 'Danone' },
      { name: 'Yoghurt aardbei Danone', category: 'dairy', price: 2.49, unit: '4x125g', brand: 'Danone' },
      { name: 'Activia natuur', category: 'dairy', price: 2.79, unit: '4x125g', brand: 'Danone' },
      { name: 'Actimel', category: 'dairy', price: 3.49, unit: '8x100ml', brand: 'Danone' },
      { name: 'Geraspte kaas Emmentaler', category: 'dairy', price: 2.49, unit: '200g', brand: 'Boni' },
      { name: 'Geraspte kaas 4 kazen', category: 'dairy', price: 2.69, unit: '200g', brand: 'Boni' },
      { name: 'Gouda jong', category: 'dairy', price: 3.29, unit: '400g', brand: 'Boni' },
      { name: 'Gouda belegen', category: 'dairy', price: 3.79, unit: '400g', brand: 'Boni' },
      { name: 'Camembert Le Rustique', category: 'dairy', price: 2.99, unit: '250g', brand: 'Le Rustique' },
      { name: 'Brie Saint-Albray', category: 'dairy', price: 3.49, unit: '200g', brand: 'Saint-Albray' },
      { name: 'Mozzarella', category: 'dairy', price: 1.49, unit: '125g', brand: 'Boni' },
      { name: 'Roomkaas Philadelphia', category: 'dairy', price: 2.29, unit: '200g', brand: 'Philadelphia' },
      { name: 'Verse room', category: 'dairy', price: 1.79, unit: '250ml', brand: 'Boni' },
      { name: 'Slagroom', category: 'dairy', price: 1.99, unit: '250ml', brand: 'Boni' },
      { name: 'Halfvolle melk 6-pack', category: 'dairy', price: 5.49, unit: '6x1L', brand: 'Boni' },
      { name: 'Chocolademelk Nesquik', category: 'dairy', price: 2.49, unit: '1L', brand: 'Nesquik' },
      { name: 'Pudding vanille', category: 'dairy', price: 1.29, unit: '4x125g', brand: 'Boni' },
      { name: 'Kwark', category: 'dairy', price: 1.19, unit: '500g', brand: 'Boni' },
      // BROOD
      { name: 'Brood wit groot', category: 'bread', price: 1.89, unit: '800g', brand: 'Boni' },
      { name: 'Brood volkoren', category: 'bread', price: 2.09, unit: '800g', brand: 'Boni' },
      { name: 'Brood meergranen', category: 'bread', price: 2.29, unit: '800g', brand: 'Boni' },
      { name: 'Pistolets wit', category: 'bread', price: 1.49, unit: '6 stuks', brand: 'Boni' },
      { name: 'Pistolets volkoren', category: 'bread', price: 1.69, unit: '6 stuks', brand: 'Boni' },
      { name: 'Toastbrood wit', category: 'bread', price: 1.29, unit: '500g', brand: 'Boni' },
      { name: 'Toastbrood volkoren', category: 'bread', price: 1.49, unit: '500g', brand: 'Boni' },
      { name: 'Croissants', category: 'bread', price: 2.49, unit: '4 stuks', brand: 'Boni' },
      { name: 'Baguette', category: 'bread', price: 0.99, unit: '1 stuk', brand: 'Boni' },
      { name: 'Ciabatta', category: 'bread', price: 1.99, unit: '1 stuk', brand: 'Boni' },
      { name: 'Wraps', category: 'bread', price: 2.29, unit: '8 stuks', brand: 'Old El Paso' },
      { name: 'Pita brood', category: 'bread', price: 1.99, unit: '6 stuks', brand: 'Boni' },
      { name: 'Brood spelt', category: 'bread', price: 2.79, unit: '600g', brand: 'Boni' },
      { name: 'Bagels', category: 'bread', price: 2.49, unit: '4 stuks', brand: 'Boni' },
      // VLEES
      { name: 'Kipfilet', category: 'meat', price: 6.99, unit: '500g', brand: 'Boni' },
      { name: 'Kippenbouten', category: 'meat', price: 4.49, unit: '1kg', brand: 'Boni' },
      { name: 'Kippendijen', category: 'meat', price: 4.99, unit: '1kg', brand: 'Boni' },
      { name: 'Gehakt gemengd', category: 'meat', price: 4.49, unit: '500g', brand: 'Boni' },
      { name: 'Gehakt rund', category: 'meat', price: 5.49, unit: '500g', brand: 'Boni' },
      { name: 'Gehakt varken', category: 'meat', price: 3.99, unit: '500g', brand: 'Boni' },
      { name: 'Hesp gekookt', category: 'meat', price: 2.99, unit: '200g', brand: 'Boni' },
      { name: 'Salami', category: 'meat', price: 2.49, unit: '150g', brand: 'Boni' },
      { name: 'Spek blokjes', category: 'meat', price: 1.99, unit: '150g', brand: 'Boni' },
      { name: 'Worst braad', category: 'meat', price: 3.49, unit: '4 stuks', brand: 'Boni' },
      { name: 'Worst cocktail Zwan', category: 'meat', price: 2.49, unit: '350g', brand: 'Zwan' },
      { name: 'Steak rund', category: 'meat', price: 8.99, unit: '300g', brand: 'Boni' },
      { name: 'Entrecote', category: 'meat', price: 11.99, unit: '300g', brand: 'Boni' },
      { name: 'Varkensgebraad', category: 'meat', price: 6.99, unit: '600g', brand: 'Boni' },
      { name: 'Lamskoteletten', category: 'meat', price: 9.99, unit: '400g', brand: 'Boni' },
      { name: 'Filet pur', category: 'meat', price: 14.99, unit: '300g', brand: 'Boni' },
      { name: 'Kipnuggets', category: 'meat', price: 3.99, unit: '400g', brand: 'Boni' },
      { name: 'Hesp Ganda', category: 'meat', price: 4.49, unit: '150g', brand: 'Ganda' },
      { name: 'Pareham', category: 'meat', price: 3.99, unit: '100g', brand: 'Boni' },
      // VIS
      { name: 'Zalm portie', category: 'fish', price: 5.99, unit: '200g', brand: 'Boni' },
      { name: 'Zalmfilet gerookt', category: 'fish', price: 4.99, unit: '100g', brand: 'Boni' },
      { name: 'Kabeljauw', category: 'fish', price: 6.99, unit: '300g', brand: 'Boni' },
      { name: 'Tonijn blik naturel Nixe', category: 'fish', price: 1.29, unit: '185g', brand: 'Nixe' },
      { name: 'Tonijn blik olijfolie', category: 'fish', price: 1.49, unit: '185g', brand: 'Nixe' },
      { name: 'Garnalen gepeld', category: 'fish', price: 5.49, unit: '150g', brand: 'Boni' },
      { name: 'Vissticks', category: 'fish', price: 2.99, unit: '400g', brand: 'Boni' },
      { name: 'Makreel blik', category: 'fish', price: 1.19, unit: '125g', brand: 'Boni' },
      { name: 'Haring', category: 'fish', price: 2.49, unit: '200g', brand: 'Boni' },
      { name: 'Mosselen', category: 'fish', price: 3.99, unit: '1kg', brand: 'Boni' },
      // GROENTEN
      { name: 'Tomaten', category: 'vegetables', price: 1.99, unit: '500g', brand: 'Boni' },
      { name: 'Cherrytomaatjes', category: 'vegetables', price: 1.79, unit: '250g', brand: 'Boni' },
      { name: 'Komkommer', category: 'vegetables', price: 0.89, unit: '1 stuk', brand: 'Boni' },
      { name: 'Paprika rood', category: 'vegetables', price: 0.99, unit: '1 stuk', brand: 'Boni' },
      { name: 'Paprika geel', category: 'vegetables', price: 0.99, unit: '1 stuk', brand: 'Boni' },
      { name: 'Paprika groen', category: 'vegetables', price: 0.89, unit: '1 stuk', brand: 'Boni' },
      { name: 'Broccoli', category: 'vegetables', price: 1.49, unit: '1 stuk', brand: 'Boni' },
      { name: 'Bloemkool', category: 'vegetables', price: 1.79, unit: '1 stuk', brand: 'Boni' },
      { name: 'Spinazie', category: 'vegetables', price: 1.99, unit: '400g', brand: 'Boni' },
      { name: 'Sla gemengd', category: 'vegetables', price: 1.69, unit: '200g', brand: 'Boni' },
      { name: 'IJsbergsla', category: 'vegetables', price: 1.29, unit: '1 stuk', brand: 'Boni' },
      { name: 'Wortelen', category: 'vegetables', price: 1.29, unit: '1kg', brand: 'Boni' },
      { name: 'Uien', category: 'vegetables', price: 1.09, unit: '1kg', brand: 'Boni' },
      { name: 'Knoflook', category: 'vegetables', price: 0.79, unit: '3 stuks', brand: 'Boni' },
      { name: 'Aardappelen', category: 'vegetables', price: 2.49, unit: '2.5kg', brand: 'Boni' },
      { name: 'Zoete aardappel', category: 'vegetables', price: 1.99, unit: '1kg', brand: 'Boni' },
      { name: 'Courgette', category: 'vegetables', price: 1.29, unit: '1 stuk', brand: 'Boni' },
      { name: 'Aubergine', category: 'vegetables', price: 1.49, unit: '1 stuk', brand: 'Boni' },
      { name: 'Prei', category: 'vegetables', price: 1.19, unit: '1 stuk', brand: 'Boni' },
      { name: 'Champignons', category: 'vegetables', price: 1.79, unit: '250g', brand: 'Boni' },
      { name: 'Avocado', category: 'vegetables', price: 1.29, unit: '1 stuk', brand: 'Boni' },
      { name: 'Maïs blik', category: 'vegetables', price: 0.99, unit: '285g', brand: 'Boni' },
      { name: 'Erwten blik', category: 'vegetables', price: 0.89, unit: '400g', brand: 'Boni' },
      { name: 'Bonen groen blik', category: 'vegetables', price: 0.89, unit: '400g', brand: 'Boni' },
      // FRUIT
      { name: 'Appelen Jonagold', category: 'fruit', price: 2.49, unit: '1kg', brand: 'Boni' },
      { name: 'Appelen Granny Smith', category: 'fruit', price: 2.69, unit: '1kg', brand: 'Boni' },
      { name: 'Peren', category: 'fruit', price: 2.49, unit: '1kg', brand: 'Boni' },
      { name: 'Bananen', category: 'fruit', price: 1.69, unit: '1kg', brand: 'Boni' },
      { name: 'Sinaasappels', category: 'fruit', price: 2.99, unit: '1kg', brand: 'Boni' },
      { name: 'Mandarijnen', category: 'fruit', price: 2.79, unit: '1kg', brand: 'Boni' },
      { name: 'Citroen', category: 'fruit', price: 0.49, unit: '1 stuk', brand: 'Boni' },
      { name: 'Aardbeien', category: 'fruit', price: 2.99, unit: '500g', brand: 'Boni' },
      { name: 'Druiven wit', category: 'fruit', price: 3.49, unit: '500g', brand: 'Boni' },
      { name: 'Druiven rood', category: 'fruit', price: 3.49, unit: '500g', brand: 'Boni' },
      { name: 'Mango', category: 'fruit', price: 1.99, unit: '1 stuk', brand: 'Boni' },
      { name: 'Ananas', category: 'fruit', price: 1.99, unit: '1 stuk', brand: 'Boni' },
      { name: 'Meloenen', category: 'fruit', price: 2.49, unit: '1 stuk', brand: 'Boni' },
      { name: 'Kiwi', category: 'fruit', price: 1.99, unit: '4 stuks', brand: 'Boni' },
      { name: 'Frambozen', category: 'fruit', price: 2.99, unit: '150g', brand: 'Boni' },
      // DRANKEN
      { name: 'Coca-Cola', category: 'drinks', price: 1.99, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Coca-Cola Zero', category: 'drinks', price: 1.99, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Fanta Orange', category: 'drinks', price: 1.89, unit: '1.5L', brand: 'Fanta' },
      { name: 'Sprite', category: 'drinks', price: 1.89, unit: '1.5L', brand: 'Sprite' },
      { name: 'Pepsi', category: 'drinks', price: 1.79, unit: '1.5L', brand: 'Pepsi' },
      { name: 'Cola Boni', category: 'drinks', price: 0.99, unit: '1.5L', brand: 'Boni' },
      { name: 'Water plat Boni', category: 'drinks', price: 0.39, unit: '1.5L', brand: 'Boni' },
      { name: 'Water bruisend Boni', category: 'drinks', price: 0.45, unit: '1.5L', brand: 'Boni' },
      { name: 'Spa Reine', category: 'drinks', price: 0.69, unit: '1.5L', brand: 'Spa' },
      { name: 'Spa Blauw', category: 'drinks', price: 0.69, unit: '1.5L', brand: 'Spa' },
      { name: 'Chaudfontaine', category: 'drinks', price: 0.79, unit: '1.5L', brand: 'Chaudfontaine' },
      { name: 'Fruitsap sinaasappel Tropicana', category: 'drinks', price: 2.99, unit: '1L', brand: 'Tropicana' },
      { name: 'Fruitsap appel', category: 'drinks', price: 1.49, unit: '1L', brand: 'Boni' },
      { name: 'Ice Tea Lipton', category: 'drinks', price: 1.79, unit: '1.5L', brand: 'Lipton' },
      { name: 'Red Bull', category: 'drinks', price: 1.49, unit: '250ml', brand: 'Red Bull' },
      { name: 'Monster Energy', category: 'drinks', price: 1.59, unit: '500ml', brand: 'Monster' },
      { name: 'Koffie gemalen Douwe Egberts', category: 'drinks', price: 5.49, unit: '250g', brand: 'Douwe Egberts' },
      { name: 'Koffie Boni', category: 'drinks', price: 3.49, unit: '250g', brand: 'Boni' },
      { name: 'Nespresso capsules', category: 'drinks', price: 3.99, unit: '10 stuks', brand: 'Nespresso' },
      { name: 'Thee Lipton', category: 'drinks', price: 2.49, unit: '25 zakjes', brand: 'Lipton' },
      { name: 'Jupiler', category: 'drinks', price: 5.99, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Stella Artois', category: 'drinks', price: 6.49, unit: '6x33cl', brand: 'Stella Artois' },
      { name: 'Duvel', category: 'drinks', price: 6.99, unit: '4x33cl', brand: 'Duvel' },
      { name: 'Leffe Blond', category: 'drinks', price: 6.49, unit: '4x33cl', brand: 'Leffe' },
      { name: 'Wijn rood Boni', category: 'drinks', price: 4.99, unit: '750ml', brand: 'Boni' },
      { name: 'Wijn wit Boni', category: 'drinks', price: 4.99, unit: '750ml', brand: 'Boni' },
      { name: 'Prosecco', category: 'drinks', price: 7.99, unit: '750ml', brand: 'Boni' },
      // SNACKS
      { name: 'Chips naturel Lays', category: 'snacks', price: 2.49, unit: '200g', brand: 'Lays' },
      { name: 'Chips paprika Lays', category: 'snacks', price: 2.49, unit: '200g', brand: 'Lays' },
      { name: 'Chips Pringles original', category: 'snacks', price: 2.99, unit: '165g', brand: 'Pringles' },
      { name: 'Chips Boni', category: 'snacks', price: 1.49, unit: '200g', brand: 'Boni' },
      { name: 'Chocolade Côte d\'Or melk', category: 'snacks', price: 2.49, unit: '200g', brand: 'Côte d\'Or' },
      { name: 'Chocolade Côte d\'Or puur', category: 'snacks', price: 2.49, unit: '200g', brand: 'Côte d\'Or' },
      { name: 'KitKat', category: 'snacks', price: 1.99, unit: '4 stuks', brand: 'Nestlé' },
      { name: 'Snickers', category: 'snacks', price: 2.49, unit: '4 stuks', brand: 'Mars' },
      { name: 'Mars', category: 'snacks', price: 2.49, unit: '4 stuks', brand: 'Mars' },
      { name: 'Twix', category: 'snacks', price: 2.49, unit: '4 stuks', brand: 'Mars' },
      { name: 'Noten mix', category: 'snacks', price: 3.49, unit: '200g', brand: 'Boni' },
      { name: 'Amandelen', category: 'snacks', price: 3.99, unit: '200g', brand: 'Boni' },
      { name: 'Rijstwafels', category: 'snacks', price: 1.79, unit: '100g', brand: 'Boni' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 2.99, unit: '400g', brand: 'Lotus' },
      { name: 'Koeken Oreo', category: 'snacks', price: 2.49, unit: '154g', brand: 'Oreo' },
      { name: 'Sultana', category: 'snacks', price: 2.29, unit: '240g', brand: 'LU' },
      { name: 'Popcorn', category: 'snacks', price: 1.99, unit: '100g', brand: 'Boni' },
      { name: 'Crackers', category: 'snacks', price: 1.49, unit: '200g', brand: 'Boni' },
      // DIEPVRIES
      { name: 'Diepvries friet McCain', category: 'frozen', price: 3.49, unit: '1kg', brand: 'McCain' },
      { name: 'Diepvries friet Boni', category: 'frozen', price: 2.29, unit: '1kg', brand: 'Boni' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.69, unit: '1kg', brand: 'Boni' },
      { name: 'Diepvries spinazie', category: 'frozen', price: 1.49, unit: '450g', brand: 'Boni' },
      { name: 'Diepvries pizza Margherita', category: 'frozen', price: 2.99, unit: '400g', brand: 'Boni' },
      { name: 'Diepvries pizza Dr. Oetker', category: 'frozen', price: 3.99, unit: '350g', brand: 'Dr. Oetker' },
      { name: 'Diepvries kip nuggets', category: 'frozen', price: 3.49, unit: '400g', brand: 'Boni' },
      { name: 'Diepvries vissticks', category: 'frozen', price: 2.99, unit: '400g', brand: 'Boni' },
      { name: 'Diepvries lasagne', category: 'frozen', price: 4.49, unit: '400g', brand: 'Boni' },
      { name: 'Ijs Magnum classic', category: 'frozen', price: 3.99, unit: '4 stuks', brand: 'Magnum' },
      { name: 'Ijs Cornetto', category: 'frozen', price: 3.49, unit: '4 stuks', brand: 'Cornetto' },
      { name: 'Ijs Ben & Jerry\'s', category: 'frozen', price: 5.99, unit: '500ml', brand: 'Ben & Jerry\'s' },
      { name: 'Diepvries erwtjes', category: 'frozen', price: 1.49, unit: '1kg', brand: 'Boni' },
      { name: 'Diepvries wok groenten', category: 'frozen', price: 2.49, unit: '1kg', brand: 'Boni' },
      // DROOG / KEUKEN
      { name: 'Pasta spaghetti Boni', category: 'other', price: 1.09, unit: '500g', brand: 'Boni' },
      { name: 'Pasta penne Boni', category: 'other', price: 1.09, unit: '500g', brand: 'Boni' },
      { name: 'Pasta Barilla', category: 'other', price: 1.79, unit: '500g', brand: 'Barilla' },
      { name: 'Rijst witte Boni', category: 'other', price: 1.79, unit: '1kg', brand: 'Boni' },
      { name: 'Rijst basmati', category: 'other', price: 2.49, unit: '1kg', brand: 'Boni' },
      { name: 'Rijst zak Uncle Ben\'s', category: 'other', price: 3.49, unit: '500g', brand: 'Uncle Ben\'s' },
      { name: 'Bloem', category: 'other', price: 0.99, unit: '1kg', brand: 'Boni' },
      { name: 'Suiker', category: 'other', price: 1.29, unit: '1kg', brand: 'Boni' },
      { name: 'Olijfolie extra vergine', category: 'other', price: 5.49, unit: '750ml', brand: 'Boni' },
      { name: 'Zonnebloemolie', category: 'other', price: 2.49, unit: '1L', brand: 'Boni' },
      { name: 'Tomatenpuree', category: 'other', price: 0.89, unit: '200g', brand: 'Boni' },
      { name: 'Tomatensaus Boni', category: 'other', price: 1.29, unit: '400g', brand: 'Boni' },
      { name: 'Tomatensaus Heinz', category: 'other', price: 1.99, unit: '400g', brand: 'Heinz' },
      { name: 'Ketchup Heinz', category: 'other', price: 2.99, unit: '500g', brand: 'Heinz' },
      { name: 'Mayonaise Boni', category: 'other', price: 1.99, unit: '500ml', brand: 'Boni' },
      { name: 'Mayonaise Devos Lemmens', category: 'other', price: 2.49, unit: '500ml', brand: 'Devos Lemmens' },
      { name: 'Mosterd', category: 'other', price: 1.29, unit: '250g', brand: 'Boni' },
      { name: 'Sojasaus', category: 'other', price: 1.99, unit: '150ml', brand: 'Kikkoman' },
      { name: 'Bouillon blokjes', category: 'other', price: 1.49, unit: '8 stuks', brand: 'Knorr' },
      { name: 'Soep tomaat Knorr', category: 'other', price: 1.99, unit: '1L', brand: 'Knorr' },
      { name: 'Cornflakes Kellogg\'s', category: 'other', price: 3.49, unit: '500g', brand: 'Kellogg\'s' },
      { name: 'Muesli', category: 'other', price: 2.99, unit: '500g', brand: 'Boni' },
      { name: 'Havermout', category: 'other', price: 1.99, unit: '500g', brand: 'Boni' },
      { name: 'Chocopasta Nutella', category: 'other', price: 3.49, unit: '400g', brand: 'Nutella' },
      { name: 'Chocopasta Boni', category: 'other', price: 1.99, unit: '400g', brand: 'Boni' },
      { name: 'Confituur aardbei', category: 'other', price: 1.99, unit: '370g', brand: 'Boni' },
      { name: 'Honing', category: 'other', price: 3.49, unit: '500g', brand: 'Boni' },
      { name: 'Zout', category: 'other', price: 0.79, unit: '1kg', brand: 'Boni' },
      { name: 'Peper zwart', category: 'other', price: 1.49, unit: '50g', brand: 'Boni' },
      // SCHOONMAAK
      { name: 'Wasmiddel Ariel vloeibaar', category: 'cleaning', price: 9.99, unit: '1.5L', brand: 'Ariel' },
      { name: 'Wasmiddel Persil', category: 'cleaning', price: 8.99, unit: '1.5L', brand: 'Persil' },
      { name: 'Wasmiddel Boni', category: 'cleaning', price: 5.99, unit: '1.5L', brand: 'Boni' },
      { name: 'Wasverzachter Lenor', category: 'cleaning', price: 5.49, unit: '1L', brand: 'Lenor' },
      { name: 'Afwasmiddel Fairy', category: 'cleaning', price: 2.99, unit: '500ml', brand: 'Fairy' },
      { name: 'Afwasmiddel Boni', category: 'cleaning', price: 1.49, unit: '500ml', brand: 'Boni' },
      { name: 'Vaatwastabletten Finish', category: 'cleaning', price: 7.99, unit: '36 stuks', brand: 'Finish' },
      { name: 'Toiletpapier Lotus', category: 'cleaning', price: 5.99, unit: '12 rollen', brand: 'Lotus' },
      { name: 'Toiletpapier Boni', category: 'cleaning', price: 3.99, unit: '12 rollen', brand: 'Boni' },
      { name: 'Keukenrol Boni', category: 'cleaning', price: 2.49, unit: '4 rollen', brand: 'Boni' },
      { name: 'Allesreiniger Dettol', category: 'cleaning', price: 3.49, unit: '500ml', brand: 'Dettol' },
      { name: 'Allesreiniger Boni', category: 'cleaning', price: 1.99, unit: '500ml', brand: 'Boni' },
      { name: 'WC reiniger', category: 'cleaning', price: 1.79, unit: '750ml', brand: 'Boni' },
      { name: 'Vuilniszakken', category: 'cleaning', price: 2.99, unit: '30 stuks', brand: 'Boni' },
      { name: 'Aluminiumfolie', category: 'cleaning', price: 1.99, unit: '20m', brand: 'Boni' },
      { name: 'Huishoudfolie', category: 'cleaning', price: 1.79, unit: '20m', brand: 'Boni' },
      // PERSOONLIJKE VERZORGING
      { name: 'Shampoo Head & Shoulders', category: 'personal', price: 4.99, unit: '400ml', brand: 'Head & Shoulders' },
      { name: 'Shampoo Boni', category: 'personal', price: 1.99, unit: '300ml', brand: 'Boni' },
      { name: 'Conditioner', category: 'personal', price: 2.49, unit: '300ml', brand: 'Boni' },
      { name: 'Douchegel Nivea', category: 'personal', price: 2.99, unit: '250ml', brand: 'Nivea' },
      { name: 'Douchegel Boni', category: 'personal', price: 1.49, unit: '250ml', brand: 'Boni' },
      { name: 'Deodorant Dove', category: 'personal', price: 3.49, unit: '150ml', brand: 'Dove' },
      { name: 'Deodorant Axe', category: 'personal', price: 3.29, unit: '150ml', brand: 'Axe' },
      { name: 'Tandpasta Colgate', category: 'personal', price: 2.49, unit: '75ml', brand: 'Colgate' },
      { name: 'Tandpasta Boni', category: 'personal', price: 1.29, unit: '75ml', brand: 'Boni' },
      { name: 'Tandenborstel Oral-B', category: 'personal', price: 3.99, unit: '1 stuk', brand: 'Oral-B' },
      { name: 'Scheermesjes Gillette', category: 'personal', price: 7.99, unit: '4 stuks', brand: 'Gillette' },
      { name: 'Scheerschuim', category: 'personal', price: 2.49, unit: '200ml', brand: 'Boni' },
      { name: 'Bodylotion Nivea', category: 'personal', price: 3.99, unit: '400ml', brand: 'Nivea' },
      { name: 'Zonnebrand SPF50', category: 'personal', price: 7.99, unit: '200ml', brand: 'Boni' },
      { name: 'Handzeep Boni', category: 'personal', price: 1.49, unit: '300ml', brand: 'Boni' },
      { name: 'Pampers maat 3', category: 'personal', price: 12.99, unit: '52 stuks', brand: 'Pampers' },
      { name: 'Maandverband Always', category: 'personal', price: 3.99, unit: '14 stuks', brand: 'Always' },
    ],
  },
  {
    id: 'delhaize',
    name: 'Delhaize',
    logo: '🦁',
    color: '#E31837',
    products: [
      // ZUIVEL
      { name: 'Bio melk halfvol', category: 'dairy', price: 1.49, unit: '1L', brand: '365' },
      { name: 'Melk halfvol', category: 'dairy', price: 1.09, unit: '1L', brand: '365' },
      { name: 'Melk vol', category: 'dairy', price: 1.15, unit: '1L', brand: '365' },
      { name: 'Boter gezouten', category: 'dairy', price: 2.79, unit: '250g', brand: '365' },
      { name: 'Boter Président', category: 'dairy', price: 3.69, unit: '250g', brand: 'Président' },
      { name: 'Eieren scharrelvlees', category: 'dairy', price: 3.99, unit: '12 stuks', brand: '365' },
      { name: 'Eieren bio', category: 'dairy', price: 5.49, unit: '12 stuks', brand: '365' },
      { name: 'Griekse yoghurt Fage', category: 'dairy', price: 2.79, unit: '500g', brand: 'Fage' },
      { name: 'Yoghurt Danone natuur', category: 'dairy', price: 2.19, unit: '500g', brand: 'Danone' },
      { name: 'Activia', category: 'dairy', price: 2.99, unit: '4x125g', brand: 'Danone' },
      { name: 'Actimel', category: 'dairy', price: 3.79, unit: '8x100ml', brand: 'Danone' },
      { name: 'Brie', category: 'dairy', price: 3.79, unit: '200g', brand: '365' },
      { name: 'Camembert', category: 'dairy', price: 3.29, unit: '250g', brand: '365' },
      { name: 'Mozzarella', category: 'dairy', price: 1.69, unit: '125g', brand: '365' },
      { name: 'Geraspte kaas', category: 'dairy', price: 2.69, unit: '200g', brand: '365' },
      { name: 'Philadelphia', category: 'dairy', price: 2.49, unit: '200g', brand: 'Philadelphia' },
      { name: 'Verse room', category: 'dairy', price: 1.99, unit: '250ml', brand: '365' },
      { name: 'Chocolademelk', category: 'dairy', price: 2.69, unit: '1L', brand: '365' },
      { name: 'Kwark', category: 'dairy', price: 1.39, unit: '500g', brand: '365' },
      { name: 'Mascarpone', category: 'dairy', price: 2.79, unit: '250g', brand: '365' },
      // BROOD
      { name: 'Zuurdesembrood', category: 'bread', price: 3.99, unit: '400g', brand: '365' },
      { name: 'Brood meergranen', category: 'bread', price: 2.79, unit: '800g', brand: '365' },
      { name: 'Brood wit', category: 'bread', price: 1.99, unit: '800g', brand: '365' },
      { name: 'Croissants vers', category: 'bread', price: 3.49, unit: '4 stuks', brand: '365' },
      { name: 'Baguette', category: 'bread', price: 1.19, unit: '1 stuk', brand: '365' },
      { name: 'Pistolets', category: 'bread', price: 1.79, unit: '6 stuks', brand: '365' },
      { name: 'Toastbrood', category: 'bread', price: 1.49, unit: '500g', brand: '365' },
      { name: 'Wraps', category: 'bread', price: 2.49, unit: '8 stuks', brand: 'Old El Paso' },
      { name: 'Bagels', category: 'bread', price: 2.79, unit: '4 stuks', brand: '365' },
      { name: 'Brood spelt bio', category: 'bread', price: 3.49, unit: '600g', brand: '365' },
      // VLEES
      { name: 'Kipfilet bio', category: 'meat', price: 9.99, unit: '500g', brand: '365' },
      { name: 'Kipfilet', category: 'meat', price: 7.49, unit: '500g', brand: '365' },
      { name: 'Entrecote', category: 'meat', price: 13.99, unit: '300g', brand: '365' },
      { name: 'Gehakt gemengd', category: 'meat', price: 5.29, unit: '500g', brand: '365' },
      { name: 'Hesp gekookt', category: 'meat', price: 3.49, unit: '200g', brand: '365' },
      { name: 'Salami', category: 'meat', price: 2.79, unit: '150g', brand: '365' },
      { name: 'Chorizo', category: 'meat', price: 3.29, unit: '150g', brand: '365' },
      { name: 'Spek', category: 'meat', price: 2.29, unit: '150g', brand: '365' },
      { name: 'Worst braad', category: 'meat', price: 3.99, unit: '4 stuks', brand: '365' },
      { name: 'Filet pur', category: 'meat', price: 15.99, unit: '300g', brand: '365' },
      // VIS
      { name: 'Zalmfilet', category: 'fish', price: 8.99, unit: '200g', brand: '365' },
      { name: 'Zalmfilet gerookt', category: 'fish', price: 5.49, unit: '100g', brand: '365' },
      { name: 'Garnalen', category: 'fish', price: 7.49, unit: '200g', brand: '365' },
      { name: 'Kabeljauw', category: 'fish', price: 7.99, unit: '300g', brand: '365' },
      { name: 'Tonijn blik', category: 'fish', price: 1.49, unit: '185g', brand: '365' },
      { name: 'Vissticks', category: 'fish', price: 3.29, unit: '400g', brand: '365' },
      { name: 'Mosselen', category: 'fish', price: 4.49, unit: '1kg', brand: '365' },
      // GROENTEN
      { name: 'Avocado', category: 'vegetables', price: 1.59, unit: '1 stuk', brand: '365' },
      { name: 'Tomaten', category: 'vegetables', price: 2.19, unit: '500g', brand: '365' },
      { name: 'Cherrytomaatjes', category: 'vegetables', price: 1.99, unit: '250g', brand: '365' },
      { name: 'Komkommer', category: 'vegetables', price: 0.99, unit: '1 stuk', brand: '365' },
      { name: 'Paprika mix', category: 'vegetables', price: 3.49, unit: '3 stuks', brand: '365' },
      { name: 'Broccoli', category: 'vegetables', price: 1.79, unit: '1 stuk', brand: '365' },
      { name: 'Champignons', category: 'vegetables', price: 1.99, unit: '250g', brand: '365' },
      { name: 'Sla gemengd', category: 'vegetables', price: 2.29, unit: '200g', brand: '365' },
      { name: 'Wortelen', category: 'vegetables', price: 1.49, unit: '1kg', brand: '365' },
      { name: 'Uien', category: 'vegetables', price: 1.19, unit: '1kg', brand: '365' },
      { name: 'Courgette', category: 'vegetables', price: 1.49, unit: '1 stuk', brand: '365' },
      { name: 'Spinazie', category: 'vegetables', price: 2.29, unit: '400g', brand: '365' },
      { name: 'Aardappelen', category: 'vegetables', price: 2.79, unit: '2.5kg', brand: '365' },
      { name: 'Zoete aardappel', category: 'vegetables', price: 2.29, unit: '1kg', brand: '365' },
      { name: 'Knoflook', category: 'vegetables', price: 0.89, unit: '3 stuks', brand: '365' },
      // FRUIT
      { name: 'Aardbeien', category: 'fruit', price: 3.99, unit: '500g', brand: '365' },
      { name: 'Bananen', category: 'fruit', price: 1.89, unit: '1kg', brand: '365' },
      { name: 'Appelen Jonagold', category: 'fruit', price: 2.79, unit: '1kg', brand: '365' },
      { name: 'Mango', category: 'fruit', price: 2.29, unit: '1 stuk', brand: '365' },
      { name: 'Druiven', category: 'fruit', price: 4.29, unit: '500g', brand: '365' },
      { name: 'Sinaasappels', category: 'fruit', price: 3.29, unit: '1kg', brand: '365' },
      { name: 'Frambozen', category: 'fruit', price: 3.49, unit: '150g', brand: '365' },
      { name: 'Kiwi', category: 'fruit', price: 2.29, unit: '4 stuks', brand: '365' },
      // DRANKEN
      { name: 'Coca-Cola', category: 'drinks', price: 2.19, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Coca-Cola Zero', category: 'drinks', price: 2.19, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Spa Reine', category: 'drinks', price: 0.79, unit: '1.5L', brand: 'Spa' },
      { name: 'Chaudfontaine', category: 'drinks', price: 0.89, unit: '1.5L', brand: 'Chaudfontaine' },
      { name: 'Water 365', category: 'drinks', price: 0.45, unit: '1.5L', brand: '365' },
      { name: 'Tropicana sinaasappel', category: 'drinks', price: 3.29, unit: '1L', brand: 'Tropicana' },
      { name: 'Ice Tea Lipton', category: 'drinks', price: 1.99, unit: '1.5L', brand: 'Lipton' },
      { name: 'Red Bull', category: 'drinks', price: 1.69, unit: '250ml', brand: 'Red Bull' },
      { name: 'Koffie Douwe Egberts', category: 'drinks', price: 5.99, unit: '250g', brand: 'Douwe Egberts' },
      { name: 'Thee Lipton', category: 'drinks', price: 2.79, unit: '25 zakjes', brand: 'Lipton' },
      { name: 'Jupiler', category: 'drinks', price: 6.49, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Leffe Blond', category: 'drinks', price: 7.29, unit: '4x33cl', brand: 'Leffe' },
      { name: 'Wijn rood 365', category: 'drinks', price: 5.99, unit: '750ml', brand: '365' },
      { name: 'Prosecco', category: 'drinks', price: 8.99, unit: '750ml', brand: '365' },
      // SNACKS
      { name: 'Chips Lays', category: 'snacks', price: 2.69, unit: '200g', brand: 'Lays' },
      { name: 'Chips Pringles', category: 'snacks', price: 3.19, unit: '165g', brand: 'Pringles' },
      { name: 'Chocolade Côte d\'Or', category: 'snacks', price: 2.79, unit: '200g', brand: 'Côte d\'Or' },
      { name: 'Noten mix', category: 'snacks', price: 4.29, unit: '200g', brand: '365' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 3.29, unit: '400g', brand: 'Lotus' },
      { name: 'Oreo', category: 'snacks', price: 2.79, unit: '154g', brand: 'Oreo' },
      { name: 'Nutella', category: 'snacks', price: 3.79, unit: '400g', brand: 'Nutella' },
      // DIEPVRIES
      { name: 'Diepvries friet McCain', category: 'frozen', price: 3.99, unit: '1kg', brand: 'McCain' },
      { name: 'Diepvries groenten 365', category: 'frozen', price: 1.99, unit: '1kg', brand: '365' },
      { name: 'Diepvries lasagne', category: 'frozen', price: 5.49, unit: '400g', brand: '365' },
      { name: 'Diepvries pizza Dr. Oetker', category: 'frozen', price: 4.49, unit: '350g', brand: 'Dr. Oetker' },
      { name: 'Ijs Ben & Jerry\'s', category: 'frozen', price: 6.49, unit: '500ml', brand: 'Ben & Jerry\'s' },
      { name: 'Ijs Magnum', category: 'frozen', price: 4.49, unit: '4 stuks', brand: 'Magnum' },
      // KEUKEN
      { name: 'Pasta Barilla', category: 'other', price: 1.99, unit: '500g', brand: 'Barilla' },
      { name: 'Rijst basmati', category: 'other', price: 2.79, unit: '1kg', brand: '365' },
      { name: 'Quinoa', category: 'other', price: 4.49, unit: '500g', brand: '365' },
      { name: 'Olijfolie extra vergine', category: 'other', price: 6.49, unit: '750ml', brand: '365' },
      { name: 'Ketchup Heinz', category: 'other', price: 3.19, unit: '500g', brand: 'Heinz' },
      { name: 'Mayonaise Devos Lemmens', category: 'other', price: 2.79, unit: '500ml', brand: 'Devos Lemmens' },
      { name: 'Bouillon Knorr', category: 'other', price: 1.79, unit: '8 stuks', brand: 'Knorr' },
      { name: 'Cornflakes Kellogg\'s', category: 'other', price: 3.99, unit: '500g', brand: 'Kellogg\'s' },
      { name: 'Havermout', category: 'other', price: 2.29, unit: '500g', brand: '365' },
      { name: 'Confituur aardbei', category: 'other', price: 2.29, unit: '370g', brand: '365' },
      { name: 'Honing', category: 'other', price: 3.99, unit: '500g', brand: '365' },
      // SCHOONMAAK
      { name: 'Wasmiddel Ariel', category: 'cleaning', price: 10.99, unit: '1.5L', brand: 'Ariel' },
      { name: 'Wasmiddel 365', category: 'cleaning', price: 6.49, unit: '1.5L', brand: '365' },
      { name: 'Afwasmiddel Fairy', category: 'cleaning', price: 3.29, unit: '500ml', brand: 'Fairy' },
      { name: 'Vaatwastabletten Finish', category: 'cleaning', price: 8.99, unit: '36 stuks', brand: 'Finish' },
      { name: 'Toiletpapier Lotus', category: 'cleaning', price: 6.49, unit: '12 rollen', brand: 'Lotus' },
      { name: 'Keukenrol', category: 'cleaning', price: 2.79, unit: '4 rollen', brand: '365' },
      { name: 'Allesreiniger Dettol', category: 'cleaning', price: 3.99, unit: '500ml', brand: 'Dettol' },
      { name: 'Vuilniszakken', category: 'cleaning', price: 3.29, unit: '30 stuks', brand: '365' },
      // PERSOONLIJKE VERZORGING
      { name: 'Shampoo Head & Shoulders', category: 'personal', price: 5.49, unit: '400ml', brand: 'Head & Shoulders' },
      { name: 'Douchegel Nivea', category: 'personal', price: 3.29, unit: '250ml', brand: 'Nivea' },
      { name: 'Deodorant Dove', category: 'personal', price: 3.99, unit: '150ml', brand: 'Dove' },
      { name: 'Tandpasta Colgate', category: 'personal', price: 2.79, unit: '75ml', brand: 'Colgate' },
      { name: 'Scheermesjes Gillette', category: 'personal', price: 8.99, unit: '4 stuks', brand: 'Gillette' },
      { name: 'Bodylotion Nivea', category: 'personal', price: 4.49, unit: '400ml', brand: 'Nivea' },
      { name: 'Pampers maat 3', category: 'personal', price: 13.99, unit: '52 stuks', brand: 'Pampers' },
      { name: 'Maandverband Always', category: 'personal', price: 4.49, unit: '14 stuks', brand: 'Always' },
    ],
  },
  {
    id: 'lidl',
    name: 'Lidl',
    logo: '🟡',
    color: '#0050AA',
    products: [
      // ZUIVEL
      { name: 'Melk halfvol Milbona', category: 'dairy', price: 0.89, unit: '1L', brand: 'Milbona' },
      { name: 'Melk vol Milbona', category: 'dairy', price: 0.95, unit: '1L', brand: 'Milbona' },
      { name: 'Boter Milbona', category: 'dairy', price: 1.99, unit: '250g', brand: 'Milbona' },
      { name: 'Eieren M', category: 'dairy', price: 2.49, unit: '10 stuks', brand: 'Milbona' },
      { name: 'Eieren L scharrelvlees', category: 'dairy', price: 3.29, unit: '10 stuks', brand: 'Milbona' },
      { name: 'Griekse yoghurt Milbona', category: 'dairy', price: 1.49, unit: '500g', brand: 'Milbona' },
      { name: 'Yoghurt aardbei Milbona', category: 'dairy', price: 1.99, unit: '4x125g', brand: 'Milbona' },
      { name: 'Kwark Milbona', category: 'dairy', price: 0.99, unit: '500g', brand: 'Milbona' },
      { name: 'Gouda jong Milbona', category: 'dairy', price: 2.49, unit: '400g', brand: 'Milbona' },
      { name: 'Geraspte kaas Milbona', category: 'dairy', price: 1.99, unit: '200g', brand: 'Milbona' },
      { name: 'Mozzarella Milbona', category: 'dairy', price: 1.29, unit: '125g', brand: 'Milbona' },
      { name: 'Verse room Milbona', category: 'dairy', price: 1.59, unit: '250ml', brand: 'Milbona' },
      { name: 'Chocolademelk Milbona', category: 'dairy', price: 1.99, unit: '1L', brand: 'Milbona' },
      { name: 'Activia Danone', category: 'dairy', price: 2.79, unit: '4x125g', brand: 'Danone' },
      { name: 'Actimel Danone', category: 'dairy', price: 3.49, unit: '8x100ml', brand: 'Danone' },
      // BROOD
      { name: 'Brood wit', category: 'bread', price: 1.29, unit: '1kg', brand: 'Lidl' },
      { name: 'Brood volkoren', category: 'bread', price: 1.49, unit: '800g', brand: 'Lidl' },
      { name: 'Toastbrood wit', category: 'bread', price: 0.99, unit: '500g', brand: 'Lidl' },
      { name: 'Toastbrood volkoren', category: 'bread', price: 1.19, unit: '500g', brand: 'Lidl' },
      { name: 'Croissants', category: 'bread', price: 1.99, unit: '6 stuks', brand: 'Lidl' },
      { name: 'Pistolets', category: 'bread', price: 1.29, unit: '6 stuks', brand: 'Lidl' },
      { name: 'Baguette', category: 'bread', price: 0.79, unit: '1 stuk', brand: 'Lidl' },
      { name: 'Bagels', category: 'bread', price: 1.99, unit: '4 stuks', brand: 'Lidl' },
      { name: 'Wraps', category: 'bread', price: 1.99, unit: '8 stuks', brand: 'Lidl' },
      { name: 'Brood meergranen', category: 'bread', price: 1.69, unit: '800g', brand: 'Lidl' },
      // VLEES
      { name: 'Kipfilet', category: 'meat', price: 5.99, unit: '500g', brand: 'Lidl' },
      { name: 'Kippenbouten', category: 'meat', price: 3.99, unit: '1kg', brand: 'Lidl' },
      { name: 'Gehakt gemengd', category: 'meat', price: 3.99, unit: '500g', brand: 'Lidl' },
      { name: 'Gehakt rund', category: 'meat', price: 4.99, unit: '500g', brand: 'Lidl' },
      { name: 'Hesp gekookt', category: 'meat', price: 2.49, unit: '200g', brand: 'Lidl' },
      { name: 'Salami', category: 'meat', price: 1.99, unit: '150g', brand: 'Lidl' },
      { name: 'Spek blokjes', category: 'meat', price: 1.79, unit: '150g', brand: 'Lidl' },
      { name: 'Worst braad', category: 'meat', price: 2.99, unit: '4 stuks', brand: 'Lidl' },
      { name: 'Kipnuggets', category: 'meat', price: 2.99, unit: '400g', brand: 'Lidl' },
      { name: 'Bacon', category: 'meat', price: 2.29, unit: '150g', brand: 'Lidl' },
      { name: 'Steak rund', category: 'meat', price: 7.99, unit: '300g', brand: 'Lidl' },
      // VIS
      { name: 'Zalm portie', category: 'fish', price: 4.99, unit: '200g', brand: 'Lidl' },
      { name: 'Zalmfilet gerookt', category: 'fish', price: 3.99, unit: '100g', brand: 'Lidl' },
      { name: 'Tonijn blik', category: 'fish', price: 0.99, unit: '185g', brand: 'Lidl' },
      { name: 'Vissticks', category: 'fish', price: 2.49, unit: '400g', brand: 'Lidl' },
      { name: 'Makreel blik', category: 'fish', price: 0.99, unit: '125g', brand: 'Lidl' },
      { name: 'Garnalen gepeld', category: 'fish', price: 4.99, unit: '150g', brand: 'Lidl' },
      // GROENTEN
      { name: 'Tomaten', category: 'vegetables', price: 1.49, unit: '500g', brand: 'Lidl' },
      { name: 'Cherrytomaatjes', category: 'vegetables', price: 1.29, unit: '250g', brand: 'Lidl' },
      { name: 'Komkommer', category: 'vegetables', price: 0.69, unit: '1 stuk', brand: 'Lidl' },
      { name: 'Paprika mix', category: 'vegetables', price: 1.99, unit: '3 stuks', brand: 'Lidl' },
      { name: 'Broccoli', category: 'vegetables', price: 1.19, unit: '1 stuk', brand: 'Lidl' },
      { name: 'Spinazie', category: 'vegetables', price: 1.69, unit: '400g', brand: 'Lidl' },
      { name: 'Sla gemengd', category: 'vegetables', price: 1.49, unit: '200g', brand: 'Lidl' },
      { name: 'Wortelen', category: 'vegetables', price: 0.99, unit: '1kg', brand: 'Lidl' },
      { name: 'Uien', category: 'vegetables', price: 0.89, unit: '1kg', brand: 'Lidl' },
      { name: 'Aardappelen', category: 'vegetables', price: 1.99, unit: '2.5kg', brand: 'Lidl' },
      { name: 'Courgette', category: 'vegetables', price: 0.99, unit: '1 stuk', brand: 'Lidl' },
      { name: 'Champignons', category: 'vegetables', price: 1.49, unit: '250g', brand: 'Lidl' },
      { name: 'Avocado', category: 'vegetables', price: 1.09, unit: '1 stuk', brand: 'Lidl' },
      { name: 'Knoflook', category: 'vegetables', price: 0.69, unit: '3 stuks', brand: 'Lidl' },
      { name: 'Prei', category: 'vegetables', price: 0.89, unit: '1 stuk', brand: 'Lidl' },
      { name: 'Bloemkool', category: 'vegetables', price: 1.49, unit: '1 stuk', brand: 'Lidl' },
      { name: 'Maïs blik', category: 'vegetables', price: 0.79, unit: '285g', brand: 'Lidl' },
      // FRUIT
      { name: 'Appelen', category: 'fruit', price: 1.99, unit: '1.5kg', brand: 'Lidl' },
      { name: 'Bananen', category: 'fruit', price: 1.29, unit: '1kg', brand: 'Lidl' },
      { name: 'Sinaasappels', category: 'fruit', price: 2.49, unit: '1kg', brand: 'Lidl' },
      { name: 'Aardbeien', category: 'fruit', price: 2.49, unit: '500g', brand: 'Lidl' },
      { name: 'Druiven', category: 'fruit', price: 2.99, unit: '500g', brand: 'Lidl' },
      { name: 'Mango', category: 'fruit', price: 1.69, unit: '1 stuk', brand: 'Lidl' },
      { name: 'Kiwi', category: 'fruit', price: 1.69, unit: '4 stuks', brand: 'Lidl' },
      { name: 'Peren', category: 'fruit', price: 1.99, unit: '1kg', brand: 'Lidl' },
      // DRANKEN
      { name: 'Coca-Cola', category: 'drinks', price: 1.79, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Coca-Cola Zero', category: 'drinks', price: 1.79, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Fanta', category: 'drinks', price: 1.69, unit: '1.5L', brand: 'Fanta' },
      { name: 'Cola Freeway', category: 'drinks', price: 0.79, unit: '1.5L', brand: 'Freeway' },
      { name: 'Water plat Saskia', category: 'drinks', price: 0.35, unit: '1.5L', brand: 'Saskia' },
      { name: 'Water bruisend Saskia', category: 'drinks', price: 0.39, unit: '1.5L', brand: 'Saskia' },
      { name: 'Fruitsap sinaasappel', category: 'drinks', price: 1.49, unit: '1L', brand: 'Lidl' },
      { name: 'Ice Tea', category: 'drinks', price: 1.49, unit: '1.5L', brand: 'Lidl' },
      { name: 'Red Bull', category: 'drinks', price: 1.39, unit: '250ml', brand: 'Red Bull' },
      { name: 'Koffie gemalen Bellarom', category: 'drinks', price: 2.99, unit: '250g', brand: 'Bellarom' },
      { name: 'Nespresso capsules Bellarom', category: 'drinks', price: 2.99, unit: '10 stuks', brand: 'Bellarom' },
      { name: 'Thee Freshona', category: 'drinks', price: 1.49, unit: '25 zakjes', brand: 'Freshona' },
      { name: 'Jupiler', category: 'drinks', price: 5.49, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Stella Artois', category: 'drinks', price: 5.99, unit: '6x33cl', brand: 'Stella Artois' },
      { name: 'Wijn rood Lidl', category: 'drinks', price: 3.99, unit: '750ml', brand: 'Lidl' },
      { name: 'Prosecco Lidl', category: 'drinks', price: 5.99, unit: '750ml', brand: 'Lidl' },
      // SNACKS
      { name: 'Chips naturel Lidl', category: 'snacks', price: 1.29, unit: '200g', brand: 'Lidl' },
      { name: 'Chips Lays', category: 'snacks', price: 2.29, unit: '200g', brand: 'Lays' },
      { name: 'Pringles', category: 'snacks', price: 2.79, unit: '165g', brand: 'Pringles' },
      { name: 'Chocolade Milka', category: 'snacks', price: 1.99, unit: '100g', brand: 'Milka' },
      { name: 'Chocolade J.D. Gross', category: 'snacks', price: 1.49, unit: '200g', brand: 'J.D. Gross' },
      { name: 'Noten mix', category: 'snacks', price: 2.99, unit: '200g', brand: 'Lidl' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 2.79, unit: '400g', brand: 'Lotus' },
      { name: 'Oreo', category: 'snacks', price: 2.29, unit: '154g', brand: 'Oreo' },
      { name: 'Koekjes Lidl', category: 'snacks', price: 0.99, unit: '200g', brand: 'Lidl' },
      { name: 'Rijstwafels', category: 'snacks', price: 1.49, unit: '100g', brand: 'Lidl' },
      { name: 'Popcorn', category: 'snacks', price: 1.49, unit: '100g', brand: 'Lidl' },
      // DIEPVRIES
      { name: 'Diepvries friet McCain', category: 'frozen', price: 3.29, unit: '1kg', brand: 'McCain' },
      { name: 'Diepvries friet Lidl', category: 'frozen', price: 1.79, unit: '1kg', brand: 'Lidl' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.49, unit: '1kg', brand: 'Lidl' },
      { name: 'Diepvries spinazie', category: 'frozen', price: 1.29, unit: '450g', brand: 'Lidl' },
      { name: 'Diepvries pizza', category: 'frozen', price: 2.79, unit: '400g', brand: 'Lidl' },
      { name: 'Diepvries kip nuggets', category: 'frozen', price: 2.49, unit: '400g', brand: 'Lidl' },
      { name: 'Diepvries vissticks', category: 'frozen', price: 2.29, unit: '400g', brand: 'Lidl' },
      { name: 'Ijs Magnum', category: 'frozen', price: 3.79, unit: '4 stuks', brand: 'Magnum' },
      { name: 'Ijs Lidl', category: 'frozen', price: 2.99, unit: '500ml', brand: 'Lidl' },
      // KEUKEN
      { name: 'Pasta spaghetti', category: 'other', price: 0.89, unit: '500g', brand: 'Lidl' },
      { name: 'Pasta penne', category: 'other', price: 0.89, unit: '500g', brand: 'Lidl' },
      { name: 'Rijst witte', category: 'other', price: 1.49, unit: '1kg', brand: 'Lidl' },
      { name: 'Rijst basmati', category: 'other', price: 1.99, unit: '1kg', brand: 'Lidl' },
      { name: 'Bloem', category: 'other', price: 0.79, unit: '1kg', brand: 'Lidl' },
      { name: 'Suiker', category: 'other', price: 0.99, unit: '1kg', brand: 'Lidl' },
      { name: 'Olijfolie', category: 'other', price: 3.99, unit: '750ml', brand: 'Lidl' },
      { name: 'Tomatensaus', category: 'other', price: 0.79, unit: '400g', brand: 'Lidl' },
      { name: 'Ketchup Heinz', category: 'other', price: 2.79, unit: '500g', brand: 'Heinz' },
      { name: 'Mayonaise', category: 'other', price: 1.79, unit: '500ml', brand: 'Lidl' },
      { name: 'Nutella', category: 'other', price: 3.29, unit: '400g', brand: 'Nutella' },
      { name: 'Chocopasta Lidl', category: 'other', price: 1.49, unit: '400g', brand: 'Lidl' },
      { name: 'Confituur aardbei', category: 'other', price: 1.79, unit: '370g', brand: 'Lidl' },
      { name: 'Cornflakes', category: 'other', price: 1.99, unit: '500g', brand: 'Lidl' },
      { name: 'Havermout', category: 'other', price: 1.49, unit: '500g', brand: 'Lidl' },
      { name: 'Bouillon blokjes', category: 'other', price: 1.29, unit: '8 stuks', brand: 'Lidl' },
      { name: 'Zout', category: 'other', price: 0.59, unit: '1kg', brand: 'Lidl' },
      // SCHOONMAAK
      { name: 'Wasmiddel W5', category: 'cleaning', price: 5.49, unit: '1.5L', brand: 'W5' },
      { name: 'Wasmiddel Ariel', category: 'cleaning', price: 9.49, unit: '1.5L', brand: 'Ariel' },
      { name: 'Wasverzachter W5', category: 'cleaning', price: 2.99, unit: '1L', brand: 'W5' },
      { name: 'Afwasmiddel W5', category: 'cleaning', price: 1.29, unit: '500ml', brand: 'W5' },
      { name: 'Vaatwastabletten W5', category: 'cleaning', price: 5.99, unit: '36 stuks', brand: 'W5' },
      { name: 'Toiletpapier Floralys', category: 'cleaning', price: 3.79, unit: '12 rollen', brand: 'Floralys' },
      { name: 'Keukenrol Floralys', category: 'cleaning', price: 2.29, unit: '4 rollen', brand: 'Floralys' },
      { name: 'Allesreiniger W5', category: 'cleaning', price: 1.49, unit: '500ml', brand: 'W5' },
      { name: 'Vuilniszakken', category: 'cleaning', price: 2.49, unit: '30 stuks', brand: 'Lidl' },
      // PERSOONLIJKE VERZORGING
      { name: 'Shampoo Cien', category: 'personal', price: 1.49, unit: '300ml', brand: 'Cien' },
      { name: 'Douchegel Cien', category: 'personal', price: 1.29, unit: '250ml', brand: 'Cien' },
      { name: 'Deodorant Cien', category: 'personal', price: 1.99, unit: '150ml', brand: 'Cien' },
      { name: 'Tandpasta Cien', category: 'personal', price: 0.99, unit: '75ml', brand: 'Cien' },
      { name: 'Tandpasta Colgate', category: 'personal', price: 2.49, unit: '75ml', brand: 'Colgate' },
      { name: 'Scheermesjes Gillette', category: 'personal', price: 7.49, unit: '4 stuks', brand: 'Gillette' },
      { name: 'Bodylotion Cien', category: 'personal', price: 1.99, unit: '400ml', brand: 'Cien' },
      { name: 'Pampers maat 3', category: 'personal', price: 11.99, unit: '52 stuks', brand: 'Pampers' },
    ],
  },
  {
    id: 'aldi',
    name: 'Aldi',
    logo: '🔵',
    color: '#00539F',
    products: [
      // ZUIVEL
      { name: 'Melk halfvol Milsani', category: 'dairy', price: 0.85, unit: '1L', brand: 'Milsani' },
      { name: 'Melk vol Milsani', category: 'dairy', price: 0.89, unit: '1L', brand: 'Milsani' },
      { name: 'Boter Milsani', category: 'dairy', price: 1.89, unit: '250g', brand: 'Milsani' },
      { name: 'Eieren M', category: 'dairy', price: 2.29, unit: '10 stuks', brand: 'Aldi' },
      { name: 'Eieren L scharrelvlees', category: 'dairy', price: 3.09, unit: '10 stuks', brand: 'Aldi' },
      { name: 'Griekse yoghurt Milsani', category: 'dairy', price: 1.29, unit: '500g', brand: 'Milsani' },
      { name: 'Yoghurt natuur Milsani', category: 'dairy', price: 0.89, unit: '500g', brand: 'Milsani' },
      { name: 'Kwark Milsani', category: 'dairy', price: 0.89, unit: '500g', brand: 'Milsani' },
      { name: 'Gouda jong Milsani', category: 'dairy', price: 2.29, unit: '400g', brand: 'Milsani' },
      { name: 'Geraspte kaas Milsani', category: 'dairy', price: 1.89, unit: '200g', brand: 'Milsani' },
      { name: 'Mozzarella Milsani', category: 'dairy', price: 1.19, unit: '125g', brand: 'Milsani' },
      { name: 'Roomkaas Milsani', category: 'dairy', price: 1.49, unit: '200g', brand: 'Milsani' },
      { name: 'Chocolademelk Milsani', category: 'dairy', price: 1.79, unit: '1L', brand: 'Milsani' },
      { name: 'Verse room Milsani', category: 'dairy', price: 1.49, unit: '250ml', brand: 'Milsani' },
      // BROOD
      { name: 'Brood wit', category: 'bread', price: 1.19, unit: '800g', brand: 'Aldi' },
      { name: 'Brood volkoren', category: 'bread', price: 1.39, unit: '800g', brand: 'Aldi' },
      { name: 'Toastbrood', category: 'bread', price: 0.89, unit: '500g', brand: 'Aldi' },
      { name: 'Croissants', category: 'bread', price: 1.99, unit: '6 stuks', brand: 'Aldi' },
      { name: 'Pistolets', category: 'bread', price: 1.19, unit: '6 stuks', brand: 'Aldi' },
      { name: 'Baguette', category: 'bread', price: 0.75, unit: '1 stuk', brand: 'Aldi' },
      { name: 'Wraps', category: 'bread', price: 1.79, unit: '8 stuks', brand: 'Aldi' },
      // VLEES
      { name: 'Kipfilet', category: 'meat', price: 5.79, unit: '500g', brand: 'Aldi' },
      { name: 'Kippenbouten', category: 'meat', price: 3.49, unit: '1kg', brand: 'Aldi' },
      { name: 'Gehakt gemengd', category: 'meat', price: 3.79, unit: '500g', brand: 'Aldi' },
      { name: 'Gehakt rund', category: 'meat', price: 4.79, unit: '500g', brand: 'Aldi' },
      { name: 'Hesp gekookt', category: 'meat', price: 2.29, unit: '200g', brand: 'Aldi' },
      { name: 'Salami', category: 'meat', price: 1.89, unit: '150g', brand: 'Aldi' },
      { name: 'Bacon', category: 'meat', price: 2.09, unit: '150g', brand: 'Aldi' },
      { name: 'Worst braad', category: 'meat', price: 2.79, unit: '4 stuks', brand: 'Aldi' },
      { name: 'Steak rund', category: 'meat', price: 7.49, unit: '300g', brand: 'Aldi' },
      // VIS
      { name: 'Zalm portie', category: 'fish', price: 4.79, unit: '200g', brand: 'Aldi' },
      { name: 'Zalmfilet gerookt', category: 'fish', price: 3.79, unit: '100g', brand: 'Aldi' },
      { name: 'Tonijn blik', category: 'fish', price: 0.89, unit: '185g', brand: 'Aldi' },
      { name: 'Vissticks', category: 'fish', price: 2.29, unit: '400g', brand: 'Aldi' },
      { name: 'Garnalen gepeld', category: 'fish', price: 4.49, unit: '150g', brand: 'Aldi' },
      // GROENTEN
      { name: 'Tomaten', category: 'vegetables', price: 1.39, unit: '500g', brand: 'Aldi' },
      { name: 'Komkommer', category: 'vegetables', price: 0.65, unit: '1 stuk', brand: 'Aldi' },
      { name: 'Paprika mix', category: 'vegetables', price: 1.79, unit: '3 stuks', brand: 'Aldi' },
      { name: 'Broccoli', category: 'vegetables', price: 1.09, unit: '1 stuk', brand: 'Aldi' },
      { name: 'Spinazie', category: 'vegetables', price: 1.59, unit: '400g', brand: 'Aldi' },
      { name: 'Wortelen', category: 'vegetables', price: 0.89, unit: '1kg', brand: 'Aldi' },
      { name: 'Uien', category: 'vegetables', price: 0.79, unit: '1kg', brand: 'Aldi' },
      { name: 'Aardappelen', category: 'vegetables', price: 1.89, unit: '2.5kg', brand: 'Aldi' },
      { name: 'Champignons', category: 'vegetables', price: 1.39, unit: '250g', brand: 'Aldi' },
      { name: 'Avocado', category: 'vegetables', price: 0.99, unit: '1 stuk', brand: 'Aldi' },
      { name: 'Knoflook', category: 'vegetables', price: 0.59, unit: '3 stuks', brand: 'Aldi' },
      { name: 'Sla gemengd', category: 'vegetables', price: 1.29, unit: '200g', brand: 'Aldi' },
      // FRUIT
      { name: 'Appelen', category: 'fruit', price: 1.79, unit: '1kg', brand: 'Aldi' },
      { name: 'Bananen', category: 'fruit', price: 1.19, unit: '1kg', brand: 'Aldi' },
      { name: 'Sinaasappels', category: 'fruit', price: 1.99, unit: '1kg', brand: 'Aldi' },
      { name: 'Aardbeien', category: 'fruit', price: 2.29, unit: '500g', brand: 'Aldi' },
      { name: 'Druiven', category: 'fruit', price: 2.79, unit: '500g', brand: 'Aldi' },
      { name: 'Mango', category: 'fruit', price: 1.49, unit: '1 stuk', brand: 'Aldi' },
      { name: 'Peren', category: 'fruit', price: 1.89, unit: '1kg', brand: 'Aldi' },
      // DRANKEN
      { name: 'Coca-Cola', category: 'drinks', price: 1.69, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Cola Aldi', category: 'drinks', price: 0.69, unit: '1.5L', brand: 'Aldi' },
      { name: 'Water plat Aldi', category: 'drinks', price: 0.29, unit: '1.5L', brand: 'Aldi' },
      { name: 'Fruitsap', category: 'drinks', price: 1.29, unit: '1L', brand: 'Aldi' },
      { name: 'Ice Tea Aldi', category: 'drinks', price: 1.29, unit: '1.5L', brand: 'Aldi' },
      { name: 'Koffie gemalen Aldi', category: 'drinks', price: 2.79, unit: '250g', brand: 'Aldi' },
      { name: 'Thee Aldi', category: 'drinks', price: 1.29, unit: '25 zakjes', brand: 'Aldi' },
      { name: 'Jupiler', category: 'drinks', price: 5.29, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Wijn rood Aldi', category: 'drinks', price: 3.49, unit: '750ml', brand: 'Aldi' },
      { name: 'Energy drink Aldi', category: 'drinks', price: 0.59, unit: '250ml', brand: 'Aldi' },
      // SNACKS
      { name: 'Chips Aldi', category: 'snacks', price: 1.19, unit: '200g', brand: 'Aldi' },
      { name: 'Chips Lays', category: 'snacks', price: 2.19, unit: '200g', brand: 'Lays' },
      { name: 'Chocolade Moser Roth', category: 'snacks', price: 1.29, unit: '125g', brand: 'Moser Roth' },
      { name: 'Noten mix Aldi', category: 'snacks', price: 2.79, unit: '200g', brand: 'Aldi' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 2.59, unit: '400g', brand: 'Lotus' },
      { name: 'Koekjes Aldi', category: 'snacks', price: 0.89, unit: '200g', brand: 'Aldi' },
      { name: 'Rijstwafels', category: 'snacks', price: 1.29, unit: '100g', brand: 'Aldi' },
      // DIEPVRIES
      { name: 'Diepvries friet Aldi', category: 'frozen', price: 1.79, unit: '1kg', brand: 'Aldi' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.29, unit: '1kg', brand: 'Aldi' },
      { name: 'Diepvries pizza', category: 'frozen', price: 2.49, unit: '400g', brand: 'Aldi' },
      { name: 'Diepvries kip nuggets', category: 'frozen', price: 2.29, unit: '400g', brand: 'Aldi' },
      { name: 'Diepvries spinazie', category: 'frozen', price: 1.19, unit: '450g', brand: 'Aldi' },
      { name: 'Ijs Aldi', category: 'frozen', price: 2.49, unit: '500ml', brand: 'Aldi' },
      // KEUKEN
      { name: 'Pasta Aldi', category: 'other', price: 0.79, unit: '500g', brand: 'Aldi' },
      { name: 'Rijst Aldi', category: 'other', price: 1.39, unit: '1kg', brand: 'Aldi' },
      { name: 'Bloem Aldi', category: 'other', price: 0.69, unit: '1kg', brand: 'Aldi' },
      { name: 'Suiker Aldi', category: 'other', price: 0.89, unit: '1kg', brand: 'Aldi' },
      { name: 'Olijfolie Aldi', category: 'other', price: 3.79, unit: '750ml', brand: 'Aldi' },
      { name: 'Tomatensaus Aldi', category: 'other', price: 0.69, unit: '400g', brand: 'Aldi' },
      { name: 'Ketchup Heinz', category: 'other', price: 2.69, unit: '500g', brand: 'Heinz' },
      { name: 'Mayonaise Aldi', category: 'other', price: 1.59, unit: '500ml', brand: 'Aldi' },
      { name: 'Chocopasta Aldi', category: 'other', price: 1.39, unit: '400g', brand: 'Aldi' },
      { name: 'Confituur aardbei Aldi', category: 'other', price: 1.59, unit: '370g', brand: 'Aldi' },
      { name: 'Cornflakes Aldi', category: 'other', price: 1.79, unit: '500g', brand: 'Aldi' },
      { name: 'Havermout Aldi', category: 'other', price: 1.29, unit: '500g', brand: 'Aldi' },
      { name: 'Bouillon blokjes', category: 'other', price: 1.09, unit: '8 stuks', brand: 'Aldi' },
      // SCHOONMAAK
      { name: 'Wasmiddel Tandil', category: 'cleaning', price: 4.99, unit: '1.5L', brand: 'Tandil' },
      { name: 'Afwasmiddel Tandil', category: 'cleaning', price: 1.19, unit: '500ml', brand: 'Tandil' },
      { name: 'Vaatwastabletten Tandil', category: 'cleaning', price: 4.99, unit: '36 stuks', brand: 'Tandil' },
      { name: 'Toiletpapier Aldi', category: 'cleaning', price: 2.99, unit: '12 rollen', brand: 'Aldi' },
      { name: 'Keukenrol Aldi', category: 'cleaning', price: 1.99, unit: '4 rollen', brand: 'Aldi' },
      { name: 'Vuilniszakken Aldi', category: 'cleaning', price: 2.19, unit: '30 stuks', brand: 'Aldi' },
      // PERSOONLIJKE VERZORGING
      { name: 'Shampoo Aldi', category: 'personal', price: 1.29, unit: '300ml', brand: 'Aldi' },
      { name: 'Douchegel Aldi', category: 'personal', price: 1.19, unit: '250ml', brand: 'Aldi' },
      { name: 'Deodorant Aldi', category: 'personal', price: 1.79, unit: '150ml', brand: 'Aldi' },
      { name: 'Tandpasta Aldi', category: 'personal', price: 0.89, unit: '75ml', brand: 'Aldi' },
      { name: 'Pampers maat 3', category: 'personal', price: 11.49, unit: '52 stuks', brand: 'Pampers' },
    ],
  },
  {
    id: 'carrefour',
    name: 'Carrefour',
    logo: '🔷',
    color: '#004A97',
    products: [
      // ZUIVEL
      { name: 'Melk halfvol Carrefour', category: 'dairy', price: 1.05, unit: '1L', brand: 'Carrefour' },
      { name: 'Melk vol', category: 'dairy', price: 1.09, unit: '1L', brand: 'Carrefour' },
      { name: 'Boter gezouten', category: 'dairy', price: 2.49, unit: '250g', brand: 'Carrefour' },
      { name: 'Boter Président', category: 'dairy', price: 3.59, unit: '250g', brand: 'Président' },
      { name: 'Eieren L', category: 'dairy', price: 3.49, unit: '12 stuks', brand: 'Carrefour' },
      { name: 'Griekse yoghurt', category: 'dairy', price: 1.89, unit: '500g', brand: 'Carrefour' },
      { name: 'Activia Danone', category: 'dairy', price: 2.89, unit: '4x125g', brand: 'Danone' },
      { name: 'Mascarpone', category: 'dairy', price: 2.59, unit: '250g', brand: 'Carrefour' },
      { name: 'Emmentaler', category: 'dairy', price: 3.39, unit: '200g', brand: 'Carrefour' },
      { name: 'Mozzarella', category: 'dairy', price: 1.59, unit: '125g', brand: 'Carrefour' },
      { name: 'Brie', category: 'dairy', price: 3.49, unit: '200g', brand: 'Carrefour' },
      { name: 'Philadelphia', category: 'dairy', price: 2.39, unit: '200g', brand: 'Philadelphia' },
      { name: 'Verse room', category: 'dairy', price: 1.89, unit: '250ml', brand: 'Carrefour' },
      { name: 'Chocolademelk', category: 'dairy', price: 2.49, unit: '1L', brand: 'Carrefour' },
      // BROOD
      { name: 'Brood wit', category: 'bread', price: 1.79, unit: '800g', brand: 'Carrefour' },
      { name: 'Baguette', category: 'bread', price: 0.99, unit: '1 stuk', brand: 'Carrefour' },
      { name: 'Pistolets', category: 'bread', price: 1.59, unit: '6 stuks', brand: 'Carrefour' },
      { name: 'Brood meergranen', category: 'bread', price: 2.29, unit: '800g', brand: 'Carrefour' },
      { name: 'Croissants', category: 'bread', price: 2.79, unit: '4 stuks', brand: 'Carrefour' },
      { name: 'Toastbrood', category: 'bread', price: 1.39, unit: '500g', brand: 'Carrefour' },
      { name: 'Wraps', category: 'bread', price: 2.29, unit: '8 stuks', brand: 'Old El Paso' },
      // VLEES
      { name: 'Kipfilet', category: 'meat', price: 7.49, unit: '500g', brand: 'Carrefour' },
      { name: 'Gehakt rund', category: 'meat', price: 5.49, unit: '500g', brand: 'Carrefour' },
      { name: 'Hesp gekookt', category: 'meat', price: 3.29, unit: '200g', brand: 'Carrefour' },
      { name: 'Chorizo', category: 'meat', price: 2.99, unit: '150g', brand: 'Carrefour' },
      { name: 'Salami', category: 'meat', price: 2.49, unit: '150g', brand: 'Carrefour' },
      { name: 'Spek', category: 'meat', price: 2.19, unit: '150g', brand: 'Carrefour' },
      { name: 'Worst braad', category: 'meat', price: 3.79, unit: '4 stuks', brand: 'Carrefour' },
      { name: 'Entrecote', category: 'meat', price: 12.99, unit: '300g', brand: 'Carrefour' },
      // VIS
      { name: 'Zalmfilet', category: 'fish', price: 6.99, unit: '200g', brand: 'Carrefour' },
      { name: 'Garnalen gepeld', category: 'fish', price: 5.99, unit: '150g', brand: 'Carrefour' },
      { name: 'Kabeljauw', category: 'fish', price: 7.49, unit: '300g', brand: 'Carrefour' },
      { name: 'Tonijn blik', category: 'fish', price: 1.29, unit: '185g', brand: 'Carrefour' },
      { name: 'Vissticks', category: 'fish', price: 2.79, unit: '400g', brand: 'Carrefour' },
      // GROENTEN
      { name: 'Tomaten', category: 'vegetables', price: 1.89, unit: '500g', brand: 'Carrefour' },
      { name: 'Sla', category: 'vegetables', price: 1.29, unit: '1 stuk', brand: 'Carrefour' },
      { name: 'Wortelen', category: 'vegetables', price: 1.19, unit: '1kg', brand: 'Carrefour' },
      { name: 'Broccoli', category: 'vegetables', price: 1.59, unit: '1 stuk', brand: 'Carrefour' },
      { name: 'Courgette', category: 'vegetables', price: 1.19, unit: '1 stuk', brand: 'Carrefour' },
      { name: 'Paprika', category: 'vegetables', price: 1.09, unit: '1 stuk', brand: 'Carrefour' },
      { name: 'Uien', category: 'vegetables', price: 1.09, unit: '1kg', brand: 'Carrefour' },
      { name: 'Aardappelen', category: 'vegetables', price: 2.49, unit: '2.5kg', brand: 'Carrefour' },
      { name: 'Champignons', category: 'vegetables', price: 1.79, unit: '250g', brand: 'Carrefour' },
      { name: 'Avocado', category: 'vegetables', price: 1.39, unit: '1 stuk', brand: 'Carrefour' },
      { name: 'Spinazie', category: 'vegetables', price: 1.99, unit: '400g', brand: 'Carrefour' },
      // FRUIT
      { name: 'Appelen', category: 'fruit', price: 2.29, unit: '1kg', brand: 'Carrefour' },
      { name: 'Peren', category: 'fruit', price: 2.49, unit: '1kg', brand: 'Carrefour' },
      { name: 'Bananen', category: 'fruit', price: 1.59, unit: '1kg', brand: 'Carrefour' },
      { name: 'Aardbeien', category: 'fruit', price: 2.99, unit: '500g', brand: 'Carrefour' },
      { name: 'Sinaasappels', category: 'fruit', price: 2.79, unit: '1kg', brand: 'Carrefour' },
      { name: 'Druiven', category: 'fruit', price: 3.49, unit: '500g', brand: 'Carrefour' },
      { name: 'Mango', category: 'fruit', price: 1.99, unit: '1 stuk', brand: 'Carrefour' },
      // DRANKEN
      { name: 'Coca-Cola', category: 'drinks', price: 1.89, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Coca-Cola Zero', category: 'drinks', price: 1.89, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Fanta', category: 'drinks', price: 1.79, unit: '1.5L', brand: 'Fanta' },
      { name: 'Mineraalwater Carrefour', category: 'drinks', price: 0.49, unit: '1.5L', brand: 'Carrefour' },
      { name: 'Spa Reine', category: 'drinks', price: 0.75, unit: '1.5L', brand: 'Spa' },
      { name: 'Fruitsap Carrefour', category: 'drinks', price: 1.79, unit: '1L', brand: 'Carrefour' },
      { name: 'Tropicana', category: 'drinks', price: 3.09, unit: '1L', brand: 'Tropicana' },
      { name: 'Ice Tea Lipton', category: 'drinks', price: 1.89, unit: '1.5L', brand: 'Lipton' },
      { name: 'Red Bull', category: 'drinks', price: 1.49, unit: '250ml', brand: 'Red Bull' },
      { name: 'Koffie Carrefour', category: 'drinks', price: 3.79, unit: '250g', brand: 'Carrefour' },
      { name: 'Jupiler', category: 'drinks', price: 5.79, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Leffe Blond', category: 'drinks', price: 6.99, unit: '4x33cl', brand: 'Leffe' },
      { name: 'Wijn rood Carrefour', category: 'drinks', price: 4.99, unit: '750ml', brand: 'Carrefour' },
      { name: 'Prosecco', category: 'drinks', price: 7.49, unit: '750ml', brand: 'Carrefour' },
      // SNACKS
      { name: 'Chips Lays', category: 'snacks', price: 2.49, unit: '200g', brand: 'Lays' },
      { name: 'Chips Carrefour', category: 'snacks', price: 1.59, unit: '200g', brand: 'Carrefour' },
      { name: 'Pringles', category: 'snacks', price: 2.99, unit: '165g', brand: 'Pringles' },
      { name: 'Chocolade Côte d\'Or', category: 'snacks', price: 2.69, unit: '200g', brand: 'Côte d\'Or' },
      { name: 'Chocolade Carrefour', category: 'snacks', price: 1.39, unit: '200g', brand: 'Carrefour' },
      { name: 'Noten mix', category: 'snacks', price: 3.49, unit: '200g', brand: 'Carrefour' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 2.99, unit: '400g', brand: 'Lotus' },
      { name: 'Oreo', category: 'snacks', price: 2.49, unit: '154g', brand: 'Oreo' },
      { name: 'Nutella', category: 'snacks', price: 3.49, unit: '400g', brand: 'Nutella' },
      // DIEPVRIES
      { name: 'Diepvries friet McCain', category: 'frozen', price: 3.49, unit: '1kg', brand: 'McCain' },
      { name: 'Diepvries friet Carrefour', category: 'frozen', price: 1.99, unit: '1kg', brand: 'Carrefour' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.69, unit: '1kg', brand: 'Carrefour' },
      { name: 'Diepvries pizza Dr. Oetker', category: 'frozen', price: 4.29, unit: '350g', brand: 'Dr. Oetker' },
      { name: 'Diepvries lasagne', category: 'frozen', price: 4.99, unit: '400g', brand: 'Carrefour' },
      { name: 'Ijs Magnum', category: 'frozen', price: 4.19, unit: '4 stuks', brand: 'Magnum' },
      { name: 'Ijs Ben & Jerry\'s', category: 'frozen', price: 6.29, unit: '500ml', brand: 'Ben & Jerry\'s' },
      // KEUKEN
      { name: 'Pasta Barilla', category: 'other', price: 1.89, unit: '500g', brand: 'Barilla' },
      { name: 'Pasta Carrefour', category: 'other', price: 1.09, unit: '500g', brand: 'Carrefour' },
      { name: 'Rijst Carrefour', category: 'other', price: 1.79, unit: '1kg', brand: 'Carrefour' },
      { name: 'Olijfolie Carrefour', category: 'other', price: 4.49, unit: '750ml', brand: 'Carrefour' },
      { name: 'Ketchup Heinz', category: 'other', price: 3.09, unit: '500g', brand: 'Heinz' },
      { name: 'Mayonaise Devos Lemmens', category: 'other', price: 2.69, unit: '500ml', brand: 'Devos Lemmens' },
      { name: 'Bouillon Knorr', category: 'other', price: 1.69, unit: '8 stuks', brand: 'Knorr' },
      { name: 'Cornflakes Kellogg\'s', category: 'other', price: 3.79, unit: '500g', brand: 'Kellogg\'s' },
      { name: 'Nutella', category: 'other', price: 3.49, unit: '400g', brand: 'Nutella' },
      { name: 'Confituur aardbei', category: 'other', price: 2.09, unit: '370g', brand: 'Carrefour' },
      // SCHOONMAAK
      { name: 'Wasmiddel Ariel', category: 'cleaning', price: 10.49, unit: '1.5L', brand: 'Ariel' },
      { name: 'Wasmiddel Carrefour', category: 'cleaning', price: 5.99, unit: '1.5L', brand: 'Carrefour' },
      { name: 'Afwasmiddel Fairy', category: 'cleaning', price: 3.09, unit: '500ml', brand: 'Fairy' },
      { name: 'Vaatwastabletten Finish', category: 'cleaning', price: 8.49, unit: '36 stuks', brand: 'Finish' },
      { name: 'Toiletpapier Carrefour', category: 'cleaning', price: 4.29, unit: '12 rollen', brand: 'Carrefour' },
      { name: 'Keukenrol Carrefour', category: 'cleaning', price: 2.69, unit: '4 rollen', brand: 'Carrefour' },
      { name: 'Allesreiniger Dettol', category: 'cleaning', price: 3.79, unit: '500ml', brand: 'Dettol' },
      { name: 'Vuilniszakken', category: 'cleaning', price: 2.99, unit: '30 stuks', brand: 'Carrefour' },
      // PERSOONLIJKE VERZORGING
      { name: 'Shampoo Head & Shoulders', category: 'personal', price: 5.29, unit: '400ml', brand: 'Head & Shoulders' },
      { name: 'Douchegel Nivea', category: 'personal', price: 3.19, unit: '250ml', brand: 'Nivea' },
      { name: 'Deodorant Dove', category: 'personal', price: 3.79, unit: '150ml', brand: 'Dove' },
      { name: 'Tandpasta Colgate', category: 'personal', price: 2.69, unit: '75ml', brand: 'Colgate' },
      { name: 'Scheermesjes Gillette', category: 'personal', price: 8.49, unit: '4 stuks', brand: 'Gillette' },
      { name: 'Pampers maat 3', category: 'personal', price: 12.49, unit: '52 stuks', brand: 'Pampers' },
      { name: 'Maandverband Always', category: 'personal', price: 4.29, unit: '14 stuks', brand: 'Always' },
    ],
  },
  {
    id: 'spar',
    name: 'Spar',
    logo: '🌲',
    color: '#00843D',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 1.19, unit: '1L', brand: 'Spar' },
      { name: 'Boter', category: 'dairy', price: 2.69, unit: '250g', brand: 'Spar' },
      { name: 'Eieren', category: 'dairy', price: 3.49, unit: '10 stuks', brand: 'Spar' },
      { name: 'Yoghurt natuur', category: 'dairy', price: 1.29, unit: '500g', brand: 'Spar' },
      { name: 'Geraspte kaas', category: 'dairy', price: 2.99, unit: '200g', brand: 'Spar' },
      { name: 'Activia Danone', category: 'dairy', price: 2.99, unit: '4x125g', brand: 'Danone' },
      { name: 'Verse room', category: 'dairy', price: 1.99, unit: '250ml', brand: 'Spar' },
      { name: 'Brood wit', category: 'bread', price: 2.09, unit: '800g', brand: 'Spar' },
      { name: 'Brood volkoren', category: 'bread', price: 2.29, unit: '800g', brand: 'Spar' },
      { name: 'Croissants', category: 'bread', price: 3.29, unit: '4 stuks', brand: 'Spar' },
      { name: 'Pistolets', category: 'bread', price: 1.79, unit: '6 stuks', brand: 'Spar' },
      { name: 'Kipfilet', category: 'meat', price: 7.99, unit: '500g', brand: 'Spar' },
      { name: 'Gehakt', category: 'meat', price: 5.29, unit: '500g', brand: 'Spar' },
      { name: 'Hesp', category: 'meat', price: 3.49, unit: '200g', brand: 'Spar' },
      { name: 'Salami', category: 'meat', price: 2.79, unit: '150g', brand: 'Spar' },
      { name: 'Zalm', category: 'fish', price: 6.49, unit: '200g', brand: 'Spar' },
      { name: 'Tonijn blik', category: 'fish', price: 1.49, unit: '185g', brand: 'Spar' },
      { name: 'Tomaten', category: 'vegetables', price: 2.19, unit: '500g', brand: 'Spar' },
      { name: 'Komkommer', category: 'vegetables', price: 0.99, unit: '1 stuk', brand: 'Spar' },
      { name: 'Paprika', category: 'vegetables', price: 1.19, unit: '1 stuk', brand: 'Spar' },
      { name: 'Sla', category: 'vegetables', price: 1.49, unit: '1 stuk', brand: 'Spar' },
      { name: 'Wortelen', category: 'vegetables', price: 1.39, unit: '1kg', brand: 'Spar' },
      { name: 'Aardappelen', category: 'vegetables', price: 2.79, unit: '2.5kg', brand: 'Spar' },
      { name: 'Appelen', category: 'fruit', price: 2.79, unit: '1kg', brand: 'Spar' },
      { name: 'Bananen', category: 'fruit', price: 1.89, unit: '1kg', brand: 'Spar' },
      { name: 'Sinaasappels', category: 'fruit', price: 3.19, unit: '1kg', brand: 'Spar' },
      { name: 'Coca-Cola', category: 'drinks', price: 2.09, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Water Spar', category: 'drinks', price: 0.89, unit: '1.5L', brand: 'Spar' },
      { name: 'Bier Jupiler', category: 'drinks', price: 6.49, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Koffie', category: 'drinks', price: 4.49, unit: '250g', brand: 'Spar' },
      { name: 'Chips Lays', category: 'snacks', price: 2.59, unit: '200g', brand: 'Lays' },
      { name: 'Chocolade Côte d\'Or', category: 'snacks', price: 2.79, unit: '200g', brand: 'Côte d\'Or' },
      { name: 'Noten mix', category: 'snacks', price: 3.99, unit: '200g', brand: 'Spar' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 3.19, unit: '400g', brand: 'Lotus' },
      { name: 'Diepvries friet', category: 'frozen', price: 2.79, unit: '1kg', brand: 'Spar' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.99, unit: '750g', brand: 'Spar' },
      { name: 'Pasta', category: 'other', price: 1.49, unit: '500g', brand: 'Spar' },
      { name: 'Rijst', category: 'other', price: 2.19, unit: '1kg', brand: 'Spar' },
      { name: 'Olijfolie', category: 'other', price: 5.49, unit: '750ml', brand: 'Spar' },
      { name: 'Ketchup Heinz', category: 'other', price: 3.19, unit: '500g', brand: 'Heinz' },
      { name: 'Wasmiddel', category: 'cleaning', price: 8.99, unit: '1.5L', brand: 'Spar' },
      { name: 'Afwasmiddel Fairy', category: 'cleaning', price: 3.29, unit: '500ml', brand: 'Fairy' },
      { name: 'Toiletpapier Lotus', category: 'cleaning', price: 6.49, unit: '12 rollen', brand: 'Lotus' },
      { name: 'Shampoo', category: 'personal', price: 3.29, unit: '300ml', brand: 'Spar' },
      { name: 'Douchegel Nivea', category: 'personal', price: 3.29, unit: '250ml', brand: 'Nivea' },
      { name: 'Tandpasta Colgate', category: 'personal', price: 2.79, unit: '75ml', brand: 'Colgate' },
    ],
  },
  {
    id: 'okay',
    name: 'OKay',
    logo: '🟠',
    color: '#F47920',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 0.99, unit: '1L', brand: 'OKay' },
      { name: 'Boter', category: 'dairy', price: 2.19, unit: '250g', brand: 'OKay' },
      { name: 'Eieren', category: 'dairy', price: 2.99, unit: '10 stuks', brand: 'OKay' },
      { name: 'Yoghurt natuur', category: 'dairy', price: 0.99, unit: '500g', brand: 'OKay' },
      { name: 'Geraspte kaas', category: 'dairy', price: 2.49, unit: '200g', brand: 'OKay' },
      { name: 'Activia Danone', category: 'dairy', price: 2.79, unit: '4x125g', brand: 'Danone' },
      { name: 'Verse room', category: 'dairy', price: 1.79, unit: '250ml', brand: 'OKay' },
      { name: 'Brood wit', category: 'bread', price: 1.69, unit: '800g', brand: 'OKay' },
      { name: 'Brood volkoren', category: 'bread', price: 1.89, unit: '800g', brand: 'OKay' },
      { name: 'Pistolets', category: 'bread', price: 1.39, unit: '6 stuks', brand: 'OKay' },
      { name: 'Croissants', category: 'bread', price: 2.49, unit: '4 stuks', brand: 'OKay' },
      { name: 'Kipfilet', category: 'meat', price: 6.49, unit: '500g', brand: 'OKay' },
      { name: 'Gehakt gemengd', category: 'meat', price: 4.29, unit: '500g', brand: 'OKay' },
      { name: 'Hesp', category: 'meat', price: 2.79, unit: '200g', brand: 'OKay' },
      { name: 'Salami', category: 'meat', price: 2.29, unit: '150g', brand: 'OKay' },
      { name: 'Zalm', category: 'fish', price: 5.49, unit: '200g', brand: 'OKay' },
      { name: 'Tonijn blik', category: 'fish', price: 1.19, unit: '185g', brand: 'OKay' },
      { name: 'Tomaten', category: 'vegetables', price: 1.79, unit: '500g', brand: 'OKay' },
      { name: 'Komkommer', category: 'vegetables', price: 0.89, unit: '1 stuk', brand: 'OKay' },
      { name: 'Paprika', category: 'vegetables', price: 0.99, unit: '1 stuk', brand: 'OKay' },
      { name: 'Wortelen', category: 'vegetables', price: 1.09, unit: '1kg', brand: 'OKay' },
      { name: 'Aardappelen', category: 'vegetables', price: 2.19, unit: '2.5kg', brand: 'OKay' },
      { name: 'Sla', category: 'vegetables', price: 1.19, unit: '1 stuk', brand: 'OKay' },
      { name: 'Broccoli', category: 'vegetables', price: 1.29, unit: '1 stuk', brand: 'OKay' },
      { name: 'Appelen', category: 'fruit', price: 2.19, unit: '1kg', brand: 'OKay' },
      { name: 'Bananen', category: 'fruit', price: 1.49, unit: '1kg', brand: 'OKay' },
      { name: 'Sinaasappels', category: 'fruit', price: 2.69, unit: '1kg', brand: 'OKay' },
      { name: 'Aardbeien', category: 'fruit', price: 2.79, unit: '500g', brand: 'OKay' },
      { name: 'Coca-Cola', category: 'drinks', price: 1.79, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Water OKay', category: 'drinks', price: 0.55, unit: '1.5L', brand: 'OKay' },
      { name: 'Fruitsap', category: 'drinks', price: 1.79, unit: '1L', brand: 'OKay' },
      { name: 'Jupiler', category: 'drinks', price: 5.79, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Koffie', category: 'drinks', price: 3.49, unit: '250g', brand: 'OKay' },
      { name: 'Chips Lays', category: 'snacks', price: 2.39, unit: '200g', brand: 'Lays' },
      { name: 'Chips OKay', category: 'snacks', price: 1.49, unit: '200g', brand: 'OKay' },
      { name: 'Chocolade Côte d\'Or', category: 'snacks', price: 2.59, unit: '200g', brand: 'Côte d\'Or' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 2.89, unit: '400g', brand: 'Lotus' },
      { name: 'Nutella', category: 'snacks', price: 3.29, unit: '400g', brand: 'Nutella' },
      { name: 'Diepvries friet', category: 'frozen', price: 2.29, unit: '1kg', brand: 'OKay' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.59, unit: '1kg', brand: 'OKay' },
      { name: 'Pasta', category: 'other', price: 1.09, unit: '500g', brand: 'OKay' },
      { name: 'Rijst', category: 'other', price: 1.79, unit: '1kg', brand: 'OKay' },
      { name: 'Olijfolie', category: 'other', price: 4.29, unit: '750ml', brand: 'OKay' },
      { name: 'Ketchup Heinz', category: 'other', price: 2.99, unit: '500g', brand: 'Heinz' },
      { name: 'Wasmiddel', category: 'cleaning', price: 7.49, unit: '1.5L', brand: 'OKay' },
      { name: 'Afwasmiddel Fairy', category: 'cleaning', price: 2.99, unit: '500ml', brand: 'Fairy' },
      { name: 'Toiletpapier', category: 'cleaning', price: 4.49, unit: '12 rollen', brand: 'OKay' },
      { name: 'Shampoo', category: 'personal', price: 2.99, unit: '300ml', brand: 'OKay' },
      { name: 'Tandpasta Colgate', category: 'personal', price: 2.59, unit: '75ml', brand: 'Colgate' },
    ],
  },
  {
    id: 'albert-heijn',
    name: 'Albert Heijn',
    logo: '🌼',
    color: '#00A0E2',
    products: [
      { name: 'Melk halfvol AH', category: 'dairy', price: 1.09, unit: '1L', brand: 'AH' },
      { name: 'Boter AH', category: 'dairy', price: 2.39, unit: '250g', brand: 'AH' },
      { name: 'Eieren AH', category: 'dairy', price: 3.19, unit: '12 stuks', brand: 'AH' },
      { name: 'Griekse yoghurt AH', category: 'dairy', price: 1.79, unit: '500g', brand: 'AH' },
      { name: 'Activia Danone', category: 'dairy', price: 2.89, unit: '4x125g', brand: 'Danone' },
      { name: 'Gouda AH', category: 'dairy', price: 3.49, unit: '400g', brand: 'AH' },
      { name: 'Mozzarella AH', category: 'dairy', price: 1.59, unit: '125g', brand: 'AH' },
      { name: 'Philadelphia', category: 'dairy', price: 2.49, unit: '200g', brand: 'Philadelphia' },
      { name: 'Verse room AH', category: 'dairy', price: 1.89, unit: '250ml', brand: 'AH' },
      { name: 'Brood wit AH', category: 'bread', price: 1.99, unit: '800g', brand: 'AH' },
      { name: 'Brood volkoren AH', category: 'bread', price: 2.19, unit: '800g', brand: 'AH' },
      { name: 'Croissants AH', category: 'bread', price: 2.99, unit: '4 stuks', brand: 'AH' },
      { name: 'Pistolets AH', category: 'bread', price: 1.69, unit: '6 stuks', brand: 'AH' },
      { name: 'Kipfilet AH', category: 'meat', price: 7.29, unit: '500g', brand: 'AH' },
      { name: 'Gehakt AH', category: 'meat', price: 4.99, unit: '500g', brand: 'AH' },
      { name: 'Hesp AH', category: 'meat', price: 3.19, unit: '200g', brand: 'AH' },
      { name: 'Zalm AH', category: 'fish', price: 6.79, unit: '200g', brand: 'AH' },
      { name: 'Garnalen AH', category: 'fish', price: 5.79, unit: '150g', brand: 'AH' },
      { name: 'Tonijn blik AH', category: 'fish', price: 1.39, unit: '185g', brand: 'AH' },
      { name: 'Tomaten AH', category: 'vegetables', price: 1.99, unit: '500g', brand: 'AH' },
      { name: 'Paprika AH', category: 'vegetables', price: 1.09, unit: '1 stuk', brand: 'AH' },
      { name: 'Broccoli AH', category: 'vegetables', price: 1.59, unit: '1 stuk', brand: 'AH' },
      { name: 'Avocado AH', category: 'vegetables', price: 1.39, unit: '1 stuk', brand: 'AH' },
      { name: 'Aardappelen AH', category: 'vegetables', price: 2.59, unit: '2.5kg', brand: 'AH' },
      { name: 'Spinazie AH', category: 'vegetables', price: 2.19, unit: '400g', brand: 'AH' },
      { name: 'Appelen AH', category: 'fruit', price: 2.39, unit: '1kg', brand: 'AH' },
      { name: 'Bananen AH', category: 'fruit', price: 1.59, unit: '1kg', brand: 'AH' },
      { name: 'Aardbeien AH', category: 'fruit', price: 3.29, unit: '500g', brand: 'AH' },
      { name: 'Druiven AH', category: 'fruit', price: 3.79, unit: '500g', brand: 'AH' },
      { name: 'Coca-Cola', category: 'drinks', price: 1.99, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Water AH', category: 'drinks', price: 0.69, unit: '1.5L', brand: 'AH' },
      { name: 'Jus d\'orange Tropicana', category: 'drinks', price: 3.19, unit: '1L', brand: 'Tropicana' },
      { name: 'Jupiler', category: 'drinks', price: 6.29, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Koffie Douwe Egberts', category: 'drinks', price: 5.49, unit: '250g', brand: 'Douwe Egberts' },
      { name: 'Chips Lays', category: 'snacks', price: 2.49, unit: '200g', brand: 'Lays' },
      { name: 'Chocolade Côte d\'Or', category: 'snacks', price: 2.79, unit: '200g', brand: 'Côte d\'Or' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 3.09, unit: '400g', brand: 'Lotus' },
      { name: 'Nutella', category: 'snacks', price: 3.69, unit: '400g', brand: 'Nutella' },
      { name: 'Diepvries friet McCain', category: 'frozen', price: 3.79, unit: '1kg', brand: 'McCain' },
      { name: 'Diepvries groenten AH', category: 'frozen', price: 1.79, unit: '1kg', brand: 'AH' },
      { name: 'Ijs Magnum', category: 'frozen', price: 4.29, unit: '4 stuks', brand: 'Magnum' },
      { name: 'Pasta Barilla', category: 'other', price: 1.99, unit: '500g', brand: 'Barilla' },
      { name: 'Rijst AH', category: 'other', price: 1.99, unit: '1kg', brand: 'AH' },
      { name: 'Olijfolie AH', category: 'other', price: 5.49, unit: '750ml', brand: 'AH' },
      { name: 'Ketchup Heinz', category: 'other', price: 3.19, unit: '500g', brand: 'Heinz' },
      { name: 'Nutella', category: 'other', price: 3.69, unit: '400g', brand: 'Nutella' },
      { name: 'Wasmiddel Ariel', category: 'cleaning', price: 10.99, unit: '1.5L', brand: 'Ariel' },
      { name: 'Toiletpapier Lotus', category: 'cleaning', price: 6.49, unit: '12 rollen', brand: 'Lotus' },
      { name: 'Shampoo Head & Shoulders', category: 'personal', price: 5.49, unit: '400ml', brand: 'Head & Shoulders' },
      { name: 'Tandpasta Colgate', category: 'personal', price: 2.79, unit: '75ml', brand: 'Colgate' },
      { name: 'Pampers maat 3', category: 'personal', price: 13.49, unit: '52 stuks', brand: 'Pampers' },
    ],
  },
  {
    id: 'match',
    name: 'Match',
    logo: '🟥',
    color: '#C8102E',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 1.15, unit: '1L', brand: 'Match' },
      { name: 'Boter', category: 'dairy', price: 2.59, unit: '250g', brand: 'Match' },
      { name: 'Eieren', category: 'dairy', price: 3.39, unit: '12 stuks', brand: 'Match' },
      { name: 'Yoghurt', category: 'dairy', price: 1.39, unit: '500g', brand: 'Match' },
      { name: 'Geraspte kaas', category: 'dairy', price: 2.79, unit: '200g', brand: 'Match' },
      { name: 'Activia Danone', category: 'dairy', price: 2.89, unit: '4x125g', brand: 'Danone' },
      { name: 'Mozzarella', category: 'dairy', price: 1.69, unit: '125g', brand: 'Match' },
      { name: 'Brood wit', category: 'bread', price: 1.99, unit: '800g', brand: 'Match' },
      { name: 'Baguette', category: 'bread', price: 1.09, unit: '1 stuk', brand: 'Match' },
      { name: 'Croissants', category: 'bread', price: 2.79, unit: '4 stuks', brand: 'Match' },
      { name: 'Kipfilet', category: 'meat', price: 7.19, unit: '500g', brand: 'Match' },
      { name: 'Gehakt', category: 'meat', price: 4.99, unit: '500g', brand: 'Match' },
      { name: 'Hesp', category: 'meat', price: 3.09, unit: '200g', brand: 'Match' },
      { name: 'Chorizo', category: 'meat', price: 2.99, unit: '150g', brand: 'Match' },
      { name: 'Zalm', category: 'fish', price: 6.29, unit: '200g', brand: 'Match' },
      { name: 'Tonijn', category: 'fish', price: 1.39, unit: '185g', brand: 'Match' },
      { name: 'Garnalen', category: 'fish', price: 5.49, unit: '150g', brand: 'Match' },
      { name: 'Tomaten', category: 'vegetables', price: 1.89, unit: '500g', brand: 'Match' },
      { name: 'Sla', category: 'vegetables', price: 1.29, unit: '1 stuk', brand: 'Match' },
      { name: 'Wortelen', category: 'vegetables', price: 1.19, unit: '1kg', brand: 'Match' },
      { name: 'Broccoli', category: 'vegetables', price: 1.49, unit: '1 stuk', brand: 'Match' },
      { name: 'Paprika', category: 'vegetables', price: 1.09, unit: '1 stuk', brand: 'Match' },
      { name: 'Aardappelen', category: 'vegetables', price: 2.39, unit: '2.5kg', brand: 'Match' },
      { name: 'Appelen', category: 'fruit', price: 2.39, unit: '1kg', brand: 'Match' },
      { name: 'Bananen', category: 'fruit', price: 1.69, unit: '1kg', brand: 'Match' },
      { name: 'Sinaasappels', category: 'fruit', price: 2.79, unit: '1kg', brand: 'Match' },
      { name: 'Druiven', category: 'fruit', price: 3.49, unit: '500g', brand: 'Match' },
      { name: 'Coca-Cola', category: 'drinks', price: 1.89, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Water', category: 'drinks', price: 0.69, unit: '1.5L', brand: 'Match' },
      { name: 'Wijn rood', category: 'drinks', price: 6.49, unit: '750ml', brand: 'Match' },
      { name: 'Jupiler', category: 'drinks', price: 6.19, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Koffie', category: 'drinks', price: 4.29, unit: '250g', brand: 'Match' },
      { name: 'Chips Lays', category: 'snacks', price: 2.49, unit: '200g', brand: 'Lays' },
      { name: 'Chocolade Côte d\'Or', category: 'snacks', price: 2.79, unit: '200g', brand: 'Côte d\'Or' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 3.09, unit: '400g', brand: 'Lotus' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.79, unit: '750g', brand: 'Match' },
      { name: 'Diepvries friet', category: 'frozen', price: 2.49, unit: '1kg', brand: 'Match' },
      { name: 'Pasta', category: 'other', price: 1.29, unit: '500g', brand: 'Match' },
      { name: 'Rijst', category: 'other', price: 1.99, unit: '1kg', brand: 'Match' },
      { name: 'Olijfolie', category: 'other', price: 4.99, unit: '750ml', brand: 'Match' },
      { name: 'Ketchup Heinz', category: 'other', price: 3.09, unit: '500g', brand: 'Heinz' },
      { name: 'Wasmiddel Ariel', category: 'cleaning', price: 9.99, unit: '1.5L', brand: 'Ariel' },
      { name: 'Toiletpapier', category: 'cleaning', price: 4.99, unit: '12 rollen', brand: 'Match' },
      { name: 'Shampoo', category: 'personal', price: 3.19, unit: '300ml', brand: 'Match' },
      { name: 'Tandpasta Colgate', category: 'personal', price: 2.69, unit: '75ml', brand: 'Colgate' },
    ],
  },
  {
    id: 'intermarche',
    name: 'Intermarché',
    logo: '🔺',
    color: '#E2001A',
    products: [
      { name: 'Melk halfvol', category: 'dairy', price: 1.05, unit: '1L', brand: 'Intermarché' },
      { name: 'Boter', category: 'dairy', price: 2.39, unit: '250g', brand: 'Intermarché' },
      { name: 'Eieren', category: 'dairy', price: 3.19, unit: '12 stuks', brand: 'Intermarché' },
      { name: 'Yoghurt', category: 'dairy', price: 1.19, unit: '500g', brand: 'Intermarché' },
      { name: 'Brie', category: 'dairy', price: 3.29, unit: '200g', brand: 'Intermarché' },
      { name: 'Activia Danone', category: 'dairy', price: 2.79, unit: '4x125g', brand: 'Danone' },
      { name: 'Mozzarella', category: 'dairy', price: 1.59, unit: '125g', brand: 'Intermarché' },
      { name: 'Brood wit', category: 'bread', price: 1.89, unit: '800g', brand: 'Intermarché' },
      { name: 'Baguette', category: 'bread', price: 0.89, unit: '1 stuk', brand: 'Intermarché' },
      { name: 'Croissants', category: 'bread', price: 2.69, unit: '4 stuks', brand: 'Intermarché' },
      { name: 'Kipfilet', category: 'meat', price: 6.99, unit: '500g', brand: 'Intermarché' },
      { name: 'Gehakt', category: 'meat', price: 4.79, unit: '500g', brand: 'Intermarché' },
      { name: 'Hesp', category: 'meat', price: 2.99, unit: '200g', brand: 'Intermarché' },
      { name: 'Chorizo', category: 'meat', price: 2.79, unit: '150g', brand: 'Intermarché' },
      { name: 'Zalm', category: 'fish', price: 6.49, unit: '200g', brand: 'Intermarché' },
      { name: 'Garnalen', category: 'fish', price: 5.49, unit: '150g', brand: 'Intermarché' },
      { name: 'Tonijn blik', category: 'fish', price: 1.29, unit: '185g', brand: 'Intermarché' },
      { name: 'Tomaten', category: 'vegetables', price: 1.79, unit: '500g', brand: 'Intermarché' },
      { name: 'Sla', category: 'vegetables', price: 1.19, unit: '1 stuk', brand: 'Intermarché' },
      { name: 'Champignons', category: 'vegetables', price: 1.89, unit: '250g', brand: 'Intermarché' },
      { name: 'Broccoli', category: 'vegetables', price: 1.49, unit: '1 stuk', brand: 'Intermarché' },
      { name: 'Wortelen', category: 'vegetables', price: 1.09, unit: '1kg', brand: 'Intermarché' },
      { name: 'Aardappelen', category: 'vegetables', price: 2.29, unit: '2.5kg', brand: 'Intermarché' },
      { name: 'Appelen', category: 'fruit', price: 2.29, unit: '1kg', brand: 'Intermarché' },
      { name: 'Bananen', category: 'fruit', price: 1.59, unit: '1kg', brand: 'Intermarché' },
      { name: 'Sinaasappels', category: 'fruit', price: 2.69, unit: '1kg', brand: 'Intermarché' },
      { name: 'Aardbeien', category: 'fruit', price: 2.99, unit: '500g', brand: 'Intermarché' },
      { name: 'Coca-Cola', category: 'drinks', price: 1.79, unit: '1.5L', brand: 'Coca-Cola' },
      { name: 'Water', category: 'drinks', price: 0.59, unit: '1.5L', brand: 'Intermarché' },
      { name: 'Wijn rood', category: 'drinks', price: 5.49, unit: '750ml', brand: 'Intermarché' },
      { name: 'Jupiler', category: 'drinks', price: 5.99, unit: '6x33cl', brand: 'Jupiler' },
      { name: 'Koffie', category: 'drinks', price: 3.99, unit: '250g', brand: 'Intermarché' },
      { name: 'Chips Lays', category: 'snacks', price: 2.39, unit: '200g', brand: 'Lays' },
      { name: 'Chocolade Côte d\'Or', category: 'snacks', price: 2.69, unit: '200g', brand: 'Côte d\'Or' },
      { name: 'Speculoos Lotus', category: 'snacks', price: 2.99, unit: '400g', brand: 'Lotus' },
      { name: 'Nutella', category: 'snacks', price: 3.39, unit: '400g', brand: 'Nutella' },
      { name: 'Diepvries groenten', category: 'frozen', price: 1.69, unit: '1kg', brand: 'Intermarché' },
      { name: 'Diepvries friet', category: 'frozen', price: 2.29, unit: '1kg', brand: 'Intermarché' },
      { name: 'Diepvries pizza', category: 'frozen', price: 3.29, unit: '400g', brand: 'Intermarché' },
      { name: 'Pasta', category: 'other', price: 1.19, unit: '500g', brand: 'Intermarché' },
      { name: 'Rijst', category: 'other', price: 1.89, unit: '1kg', brand: 'Intermarché' },
      { name: 'Olijfolie', category: 'other', price: 4.39, unit: '750ml', brand: 'Intermarché' },
      { name: 'Ketchup Heinz', category: 'other', price: 2.99, unit: '500g', brand: 'Heinz' },
      { name: 'Mayonaise Devos Lemmens', category: 'other', price: 2.59, unit: '500ml', brand: 'Devos Lemmens' },
      { name: 'Wasmiddel Ariel', category: 'cleaning', price: 9.79, unit: '1.5L', brand: 'Ariel' },
      { name: 'Toiletpapier Lotus', category: 'cleaning', price: 5.99, unit: '12 rollen', brand: 'Lotus' },
      { name: 'Afwasmiddel Fairy', category: 'cleaning', price: 3.09, unit: '500ml', brand: 'Fairy' },
      { name: 'Shampoo', category: 'personal', price: 3.09, unit: '300ml', brand: 'Intermarché' },
      { name: 'Tandpasta Colgate', category: 'personal', price: 2.59, unit: '75ml', brand: 'Colgate' },
      { name: 'Pampers maat 3', category: 'personal', price: 12.29, unit: '52 stuks', brand: 'Pampers' },
    ],
  },
];